[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
(
      \.github/
    | \.history/
    | config/
    | docs/
    | lib/
    | src/
)
''' 

[pep8]
ignore = E401,E203,W503,C901,E501,E722,E302,E303,E306,E741,F841,W605,E721