//! Build script: computes `SCHEMA_HASH` (SHA-256 over the canonicalized
//! schema text) and emits two generated files.
//!
//! 1. `$OUT_DIR/schema_hash.rs` — `pub const SCHEMA_HASH: [u8; 32] = ...;`
//!    `include!`'d by `src/lib.rs`. We can't compute SHA-256 in `const fn`
//!    today, so a build script is the natural place.
//!
//! 2. `../../src/kalico_protocol_schema.h` — C header consumed by the MCU
//!    dispatcher. **Note the path-out-of-tree:** we deliberately write into
//!    the kalico repo's top-level `src/` (Klipper firmware tree) rather than
//!    this crate's directory because the MCU C build expects all firmware
//!    headers under `src/`. This is unconventional for a Cargo build script;
//!    the alternative (writing into `OUT_DIR` and copying via `xtask`) was
//!    rejected as additional moving parts for what is effectively a single
//!    artifact the C build needs alongside `command.h` etc.
//!
//! The schema definition (`SCHEMA_MESSAGES`, `BOOTSTRAP_TAGS`,
//! `canonicalize_schema`) is shared with `tests/schema_hash_change.rs` via
//! `include!("schema_def.rs")`.

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::PathBuf;

include!("schema_def.rs");

const PROTO_VERSION: u8 = 0x01;

fn main() {
    println!("cargo:rerun-if-changed=schema_def.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let canonical = canonicalize_schema(SCHEMA_MESSAGES);
    let mut hasher = Sha256::new();
    hasher.update(canonical.as_bytes());
    let hash: [u8; 32] = hasher.finalize().into();

    // 1. Rust constant.
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let mut rs = String::new();
    rs.push_str("// Generated by build.rs. Do not edit.\n");
    rs.push_str("pub const SCHEMA_HASH: [u8; 32] = [");
    for (i, b) in hash.iter().enumerate() {
        if i > 0 {
            rs.push_str(", ");
        }
        rs.push_str(&format!("0x{b:02x}"));
    }
    rs.push_str("];\n");
    rs.push_str(&format!(
        "pub const SCHEMA_HASH_HEX: &str = \"{}\";\n",
        hex_string(&hash)
    ));
    // Expose canonical text for diagnostics / debugging.
    rs.push_str("pub const SCHEMA_CANONICAL: &str = ");
    rs.push_str(&rust_string_literal(&canonical));
    rs.push_str(";\n");
    fs::write(out_dir.join("schema_hash.rs"), rs).expect("write schema_hash.rs");

    // 2. C header — written to ../../src/kalico_protocol_schema.h, i.e. the
    //    kalico repo's top-level firmware src/ directory. See module-level
    //    comment for rationale.
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let header_path = manifest_dir
        .join("..")
        .join("..")
        .join("src")
        .join("kalico_protocol_schema.h");

    let mut h = String::new();
    h.push_str("/* Generated by rust/kalico-protocol/build.rs. Do not edit. */\n");
    h.push_str(
        "/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */\n",
    );
    h.push_str("#ifndef KALICO_PROTOCOL_SCHEMA_H\n");
    h.push_str("#define KALICO_PROTOCOL_SCHEMA_H\n\n");
    h.push_str("#include <stdint.h>\n\n");
    h.push_str(&format!(
        "#define KALICO_PROTO_VERSION 0x{PROTO_VERSION:02x}\n\n"
    ));

    h.push_str("/* Bootstrap message type tags (fixed-layout per spec §5). */\n");
    for (tag, name) in BOOTSTRAP_TAGS {
        h.push_str(&format!(
            "#define KALICO_MSG_{} 0x{:04x}\n",
            upper_snake(name),
            tag
        ));
    }
    h.push('\n');

    h.push_str("/* Schema-validated message type tags. */\n");
    for m in SCHEMA_MESSAGES {
        h.push_str(&format!(
            "#define KALICO_MSG_{} 0x{:04x}\n",
            upper_snake(m.name),
            m.type_tag
        ));
    }
    h.push('\n');

    h.push_str("/* SHA-256 over canonicalized schema (excludes bootstrap). */\n");
    h.push_str("static const uint8_t KALICO_SCHEMA_HASH[32] = {\n    ");
    for (i, b) in hash.iter().enumerate() {
        if i > 0 {
            h.push_str(", ");
            if i % 8 == 0 {
                h.push_str("\n    ");
            }
        }
        h.push_str(&format!("0x{b:02x}"));
    }
    h.push_str("\n};\n\n");

    h.push_str("#endif /* KALICO_PROTOCOL_SCHEMA_H */\n");

    // Guard: skip header generation only when `src/` doesn't exist at all —
    // that is the standalone-crate-publish path where the firmware tree is
    // absent. Any other failure (disk full, permissions, …) is a hard error:
    // a silently stale C header violates the deploy-lockstep guarantee.
    if let Some(parent) = header_path.parent() {
        if !parent.exists() {
            // Standalone-crate-publish: firmware src/ absent — skip silently.
            println!(
                "cargo:warning=kalico-protocol: skipping C header generation; {} does not exist \
                 (standalone-crate-publish path — expected)",
                parent.display()
            );
            return;
        }
    }
    // src/ exists — any write failure is fatal.
    fs::write(&header_path, h).unwrap_or_else(|e| {
        panic!(
            "kalico-protocol build.rs: failed to write C header {}: {e}\n\
             (src/ exists but write failed — disk full, permissions issue, or path wrong)",
            header_path.display()
        )
    });
}

fn upper_snake(name: &str) -> String {
    // CamelCase -> UPPER_SNAKE_CASE. ASCII only; all message names are ASCII.
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

fn hex_string(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn rust_string_literal(s: &str) -> String {
    // Use raw string with enough `#`s to avoid escaping. Schema text only
    // contains ASCII printable chars + `\n`, so a regular escaped literal is
    // simpler and reviewable.
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
