//! Cubic-Bezier curve pool slots.
//!
//! Each slot holds up to `MAX_PIECES_PER_CURVE` pieces of one per-axis cubic
//! Bezier curve in monomial form. Replaces the NURBS storage that lived in
//! the prior `curve_pool` slot layout.
//!
//! Slot+generation discipline (`try_alloc_and_load`, `lookup`, `confirm_retired`)
//! is owned by `crate::curve_pool` and unchanged by this redesign. This module
//! defines only the slot's *payload* shape and the conversion / validation
//! used at load time.
//!
//! Spec: `docs/superpowers/specs/2026-05-20-stepping-redesign-finish-design.md` §2, §3.2.

use crate::monomial::{bernstein_to_monomial_with_duration, BezierPieceMonomial};

// Sizing constants are generated by `build.rs` into `OUT_DIR/sizing.rs` and
// included verbatim. `curve_pool.rs` uses the same pattern; there is no
// `crate::sizing` module path.
include!(concat!(env!("OUT_DIR"), "/sizing.rs"));

/// A loaded per-axis curve: the array of monomial-form pieces the ISR walks
/// via a (curve_handle, piece_cursor) pair on `AxisConfig`.
#[repr(C)]
#[derive(Debug)]
pub struct LoadedCubicCurve {
    pub piece_count: u16,
    pub _pad: [u8; 2],
    pub pieces: [BezierPieceMonomial; MAX_PIECES_PER_CURVE],
}

impl LoadedCubicCurve {
    /// Construct an empty curve (all pieces zeroed, count=0).
    /// Used by the curve_pool slot initializer.
    pub const fn empty() -> Self {
        const ZERO_PIECE: BezierPieceMonomial = BezierPieceMonomial {
            coeffs: [0.0; 4],
            vel_coeffs: [0.0; 3],
            duration: 0.0,
        };
        Self {
            piece_count: 0,
            _pad: [0; 2],
            pieces: [ZERO_PIECE; MAX_PIECES_PER_CURVE],
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum CubicLoadError {
    PieceCountOutOfRange,
    NonFiniteBernstein,
    NonPositiveDuration,
}

/// Per-piece wire entry decoded from the load_curve_cubic blob:
/// 4 Bernstein bits + duration bits, each u32 (f32 bit pattern).
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct WirePiece {
    pub bp0_bits: u32,
    pub bp1_bits: u32,
    pub bp2_bits: u32,
    pub bp3_bits: u32,
    pub duration_bits: u32,
}

/// Convert a wire piece array into a populated `LoadedCubicCurve`.
///
/// Validates each piece's Bernstein control points are finite and
/// duration is finite and positive. Returns `Err` without mutating `out`
/// on the first invalid piece, so the caller can leave the slot untouched.
pub fn populate_from_wire(
    out: &mut LoadedCubicCurve,
    wire: &[WirePiece],
) -> Result<(), CubicLoadError> {
    if wire.is_empty() || wire.len() > MAX_PIECES_PER_CURVE {
        return Err(CubicLoadError::PieceCountOutOfRange);
    }
    // Phase 1: validate every piece WITHOUT writing into `out`.
    for w in wire {
        let bp = [
            f32::from_bits(w.bp0_bits),
            f32::from_bits(w.bp1_bits),
            f32::from_bits(w.bp2_bits),
            f32::from_bits(w.bp3_bits),
        ];
        if bp.iter().any(|x| !x.is_finite()) {
            return Err(CubicLoadError::NonFiniteBernstein);
        }
        let d = f32::from_bits(w.duration_bits);
        if !d.is_finite() || d <= 0.0 {
            return Err(CubicLoadError::NonPositiveDuration);
        }
    }
    // Phase 2: all valid → populate.
    for (i, w) in wire.iter().enumerate() {
        let bp = [
            f32::from_bits(w.bp0_bits),
            f32::from_bits(w.bp1_bits),
            f32::from_bits(w.bp2_bits),
            f32::from_bits(w.bp3_bits),
        ];
        let d = f32::from_bits(w.duration_bits);
        out.pieces[i] = bernstein_to_monomial_with_duration(bp, d);
    }
    out.piece_count = wire.len() as u16;
    Ok(())
}
