//! Compile-time sizing constants generated by `runtime/build.rs`.
//!
//! `RT_STORAGE_SIZE`, `PIECE_RING_SIZE`, and `TOTAL_RING_PIECES` are written
//! into `$OUT_DIR/sizing.rs` by the build script and included here. All
//! consumers that previously re-exported these from `curve_pool` now import
//! from this module.
//!
//! `RT_STORAGE_SIZE` — byte ceiling for the C-declared `rt_storage` buffer.
//! `PIECE_RING_SIZE` — total byte budget for all per-axis piece ring buffers.
//! `TOTAL_RING_PIECES` — maximum piece entries across all axes combined
//!   (`PIECE_RING_SIZE / 32`).

include!(concat!(env!("OUT_DIR"), "/sizing.rs"));
