//! Half-split runtime state per Step-6 spec §11.
//!
//! `FgState` is touched only from foreground command-dispatch.
//! `IsrState` is touched only from the TIM5 ISR.
//! `SharedState` is touched concurrently from both via atomics only.
//!
//! Discipline contract: code-review-enforced. No compiler check. The TIM5
//! ISR is the SOLE writer of `IsrState`; any other interrupt that needs MCU
//! state goes through `SharedState` atomics.
//!
//! `TickState` is the per-tick struct shared with the PA/IS slot pipeline
//! and predates the half-split — it stays in this module.

// The half-split FFI projection (see `init` below) needs raw-pointer writes
// through `MaybeUninit` and an `unsafe impl Sync` for `RuntimeContext`; the
// foreign symbol declarations for `runtime_clock_freq` / `irq_save` /
// `irq_restore` also require `unsafe extern "C"`. Workspace lints deny
// `unsafe_code` globally — this module opts out with the rationale documented
// inline.
#![allow(unsafe_code)]

use core::cell::UnsafeCell;
use core::sync::atomic::{AtomicBool, AtomicI32, AtomicU8, AtomicU16, AtomicU32};
// `AtomicU64` comes from `portable-atomic` because thumbv7em-none-eabi[hf]
// (Cortex-M7) lacks native 64-bit CAS — `core::sync::atomic::AtomicU64` is
// not provided on that target. `portable-atomic`'s `fallback` feature
// implements u64 atomics via a critical section, which is correct for our
// usage (counters bumped from the producer/consumer paths and read by the
// foreground). API is drop-in compatible with `core::sync::atomic::AtomicU64`.
use portable_atomic::AtomicU64;

use crate::clock::WidenState;
use crate::engine::Engine;
use crate::piece_ring::PieceEntry;

/// Runtime storage size — the byte count the C side must reserve for
/// `RuntimeContext`. Generated by `runtime/build.rs` into `$OUT_DIR/sizing.rs`.
/// Use `runtime::RT_STORAGE_SIZE` in external crates.
pub use crate::sizing::RT_STORAGE_SIZE;

/// Total number of piece entries in the shared ring storage.
/// Derived from `PIECE_RING_SIZE / 32` (each entry is 32 bytes).
pub use crate::sizing::TOTAL_RING_PIECES;

/// Byte size of the piece ring storage (compile-time constant from build.rs).
pub use crate::sizing::PIECE_RING_SIZE;

/// Per-stepper stepping-output strategy. Stored as `AtomicU8` in
/// `SharedState::step_modes`; runtime-mutable via `runtime_set_step_mode`.
///
/// Spec: docs/superpowers/specs/2026-05-12-step-time-scheduling-design.md §3.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum StepMode {
    /// Driven by TIM5 ISR at the MCU's modulation rate. Current behavior
    /// (polled curve eval + `StepAccumulator`). Future: grows to include
    /// sin/cos commutation per build-order Step 10.
    Modulated = 0,
    /// Driven by per-stepper Klipper `struct timer`. Engine computes each
    /// step's firing time via Newton iteration on the position polynomial.
    /// Default for all steppers; mandatory on MCUs that don't advertise
    /// the `PHASE_STEPPING` capability bit.
    StepTime = 1,
}

impl StepMode {
    pub fn from_u8(raw: u8) -> Option<StepMode> {
        match raw {
            0 => Some(StepMode::Modulated),
            1 => Some(StepMode::StepTime),
            _ => None,
        }
    }
}

/// Per-MCU stepper oid counter slots for homing snapshots and the
/// phase-stepping per-motor (bus_id, cs_pin_id, slot_idx) table.
///
/// 16 entries support a CoreXY+AWD (4 phase-stepped motors), full-Cartesian
/// (4 motors with no AWD), and headroom for N-motor-per-slot industrial
/// configurations up to a hard cap of 16 phase-stepped motors per MCU.
/// Memory cost is modest: each entry adds 1 (`AtomicU8` phase_slot_idx) +
/// 2 (`AtomicU16` phase_config) + 4 (`AtomicI32` stepper_counts) +
/// 1 (`AtomicU8` step_modes) ≈ 8 bytes; bumping 8 → 16 costs ~64 bytes.
pub const MAX_STEPPER_OIDS: usize = 16;

/// Per-tick state shared with PA/IS slots. Spec §3.1.
#[derive(Debug, Clone, Copy)]
pub struct TickState {
    pub dt: f32,
    pub positions: [f32; 4], // [x, y, z, e] logical
    pub motors: [f32; 4],    // [a, b, z, e] or [x, y, z, e] post-kinematic
}

/// Production `Engine` type alias — the PA/IS generic params have been removed
/// in the Task 6 rewrite (host pre-bakes them).  The alias is kept so all
/// existing call sites (`IsrState::engine`, `init`, FFI) compile without
/// changes to their type annotations.
pub type EngineImpl = Engine;

// Phase 7 §8.5 force_idle handshake calls Klipper's `irq_save`/`irq_restore`
// to gate the queue-drain step. We import via thin C wrappers
// `runtime_irq_save` / `runtime_irq_restore` defined in `src/runtime_tick.c`,
// not the bare functions directly: Klipper's MCU build uses
// `-flto=auto -fwhole-program`, which empirically lets the LTO/whole-program
// inliner DCE the standalone `irq_save` / `irq_restore` symbols (their
// bodies get inlined at every Klipper callsite) — leaving the kalico
// staticlib's references unresolvable at the final link. The wrappers are
// marked `used + externally_visible` on the C side so LTO keeps them.
unsafe extern "C" {
    pub fn runtime_irq_save() -> u32;
    pub fn runtime_irq_restore(flags: u32);
}

/// Foreground-only state. Touched exclusively by the command-dispatch task.
#[derive(Debug)]
pub struct FgState {
    /// Stream-open identity tracking for §8.5 idempotency (same-`stream_id` rule).
    pub current_stream_id: Option<u32>,
    /// Arm-time idempotency (§8.5: arm with same `t_start_t0` returns OK).
    pub armed_t_start_t0: Option<u64>,
    /// Used by §8.5 flush spin-wait deadline computation.
    pub flush_start_tick: Option<u64>,
}

/// ISR-half state. Written exclusively by the TIM5 ISR
/// (`kalico_runtime_tick_sample`). Mutual exclusion is enforced by
/// Cortex-M NVIC priority arbitration.
#[allow(missing_debug_implementations)] // Engine doesn't implement Debug.
#[repr(C)]
pub struct IsrState {
    pub engine: EngineImpl,
    /// CYCCNT widening. The ISR is the sole writer; foreground must not call
    /// `widen()` directly.
    pub widen_state: WidenState,
    /// Widened `now` from the previous `isr_sample_tick` call.
    /// `None` until the first active tick sets a baseline; used by the
    /// inter-arrival guard to detect starvation before acting on stale time.
    /// Set to `Some` only when the previous tick had active motion; idle ticks
    /// clear it to `None` so the guard never fires during boot/config.
    pub last_tick_now: Option<u64>,
}

impl IsrState {
    /// Return a raw const pointer to the `IsrState` inside `ctx`.
    ///
    /// Used by `engine::arm_step_timer_for_stepper` to form a shared reference
    /// to the ISR-owned engine and curve-pool state without taking `&mut
    /// IsrState`. The caller is responsible for the aliasing discipline (see
    /// the function's SAFETY doc).
    pub fn raw_ref_from_ctx(ctx: &RuntimeContext) -> *const Self {
        // `addr_of!` does not form a reference; `raw_get` returns a raw
        // pointer from the UnsafeCell without any unsafe operation.
        // The caller is responsible for upholding the non-exclusive borrow
        // invariant when it dereferences the returned pointer.
        core::cell::UnsafeCell::raw_get(core::ptr::addr_of!(ctx.isr))
    }
}

/// Cross-half shared state. Atomics only; no `&mut` reaches this struct.
#[derive(Debug)]
#[repr(C)]
pub struct SharedState {
    // Step-5 carryover.
    pub last_error: AtomicI32,
    pub runtime_status: AtomicU8,
    // Step-6: stream lifecycle (§8).
    pub stream_open: AtomicBool,
    // Step-6: flush handshake (Plan-decision A — foreground sets force_idle
    // FIRST, ack-waits, THEN clears stream_open).
    pub force_idle: AtomicBool,
    pub acked_force_idle: AtomicBool,
    // Step-6: §11.4 widened-clock seqlock — foreground reads, ISR writes.
    pub widened_now_lo: AtomicU32,
    pub widened_now_hi: AtomicU32,
    pub widened_now_seq: AtomicU32,
    // Step-6: §13.1 trace-overflow latch (ISR sets, foreground latches fault).
    pub sample_drop_pending: AtomicBool,
    /// 2026-05-17 F4-retire-stall diagnostic: low 32 bits of the most
    /// recent `now - seg.t_start` value computed inside
    /// `runtime_modulated_tick`. Exposed via fault_detail tag 0xFB. If
    /// this stays at 0 while a segment is queued, the engine's clock
    /// (`now` from `runtime_widened_host_clock`) is stuck or behind
    /// `seg.t_start`, so the `elapsed >= duration` retirement check
    /// can never fire.
    pub last_modulated_elapsed_lo: AtomicU32,
    /// Companion to `last_modulated_elapsed_lo`: low 32 bits of the
    /// active segment's `duration()`. Exposed via fault_detail tag 0xFC.
    /// Comparing tag 0xFB ≥ tag 0xFC tells us whether the retirement
    /// branch should fire on the next tick.
    pub last_modulated_duration_lo: AtomicU32,
    /// 2026-05-17 F4 retire-stall diagnostic: increments on every entry
    /// into `runtime_modulated_tick`'s `elapsed >= duration` branch.
    /// If this stays 0, retirement isn't being reached (clock not
    /// advancing past t_start + duration). If > 0 but
    /// `retired_through_segment_id` stays 0, the retirement branch
    /// enters but consumers_done returns false (motor bits not cleared).
    pub modulated_retire_attempts: AtomicU32,
    /// Increments on every successful retirement (consumers_done == true
    /// path). Should equal `modulated_retire_attempts` if the consumers
    /// mask is being cleared correctly.
    pub modulated_retire_successes: AtomicU32,
    /// 2026-05-17: snapshot of `seg.consumers_remaining` AFTER the
    /// clear-all-motors loop in modulated_tick's retirement branch.
    /// If non-zero, the clear loop missed bits that compute_consumers_remaining
    /// set — the remaining bits tell us which positions need investigation.
    pub last_retire_consumers_after_clear: AtomicU32,
    /// §9.2 + §5.3 — last latched fault's encoded `fault_detail` payload.
    /// Set in lockstep with `last_error` whenever a fault latches; read by
    /// the periodic 10 Hz `kalico_status_v6` frame and the async
    /// `kalico_fault` event so the host can decode the fault context
    /// (slot index, observed/expected generation, etc.) per spec §9.2.
    /// `0` when no fault has latched OR when the fault carries no
    /// per-event detail.
    pub fault_detail: AtomicU32,
    // Step 7-D: signed per-stepper pulse counters, indexed by stepper oid.
    pub stepper_counts: [AtomicI32; MAX_STEPPER_OIDS],
    /// Per-stepper `StepMode` (spec §5). Atomic so the host can flip a
    /// stepper between Modulated and StepTime at runtime (needed for future
    /// sensorless homing on phase-stepped axes — TMC StallGuard requires
    /// the driver's internal sequencer, which the direct/phase-stepping
    /// path bypasses). Default `StepTime` (enum value 1).
    pub step_modes: [AtomicU8; MAX_STEPPER_OIDS],
    /// Per-motor phase-stepping SPI config. Packed (`spi_bus_id << 8 |
    /// cs_pin_id`). `0xFFFF` means "no phase config — use the StepPulse
    /// output path." Populated during axis configuration; read by
    /// `runtime_modulated_tick`. See `crate::phase_config` for the helpers.
    ///
    /// In the variable-length layout (≥26-byte body), entry `motor_idx`
    /// describes the SPI bus / CS pin for the physical motor at
    /// `motor_idx`. The kinematic slot whose commanded `motors[slot_idx]`
    /// position drives this motor's XDIRECT output is in
    /// `phase_slot_idx[motor_idx]`. Multiple motors may share a slot
    /// (AWD pairs, N-motor-per-axis industrial configs).
    pub phase_config: [AtomicU16; MAX_STEPPER_OIDS],
    /// Per-motor kinematic-slot mapping. `phase_slot_idx[motor_idx]` is
    /// the slot whose commanded `motors[slot_idx]` position drives motor
    /// `motor_idx`'s XDIRECT output. Multiple motors can share a slot
    /// (AWD pairs, or industrial multi-motor-per-axis configs).
    /// Populated during axis configuration alongside `phase_config`.
    /// Unused entries hold `0xFF`.
    pub phase_slot_idx: [AtomicU8; MAX_STEPPER_OIDS],
    /// Number of valid entries in `phase_config` / `phase_slot_idx`. The
    /// ISR loops `0..phase_motor_count` rather than scanning the full
    /// `MAX_STEPPER_OIDS` array. Stored as `AtomicU8` so the foreground
    /// can re-publish a fresh count from the configure path. `0`
    /// disables phase stepping entirely on this MCU.
    pub phase_motor_count: AtomicU8,


    // ─── Step 7-emission (Task 5) diagnostics ─────────────────────────────
    // Spec: docs/superpowers/specs/2026-05-14-step-emission-architecture-design.md §6.
    /// Dedupe flag for producer-timer kicks. Kickers (push_segment + the
    /// per-motor consumer low-water hook) CAS-set this `false→true`; the
    /// CAS-winner schedules the producer struct timer. The producer clears
    /// this on entry. A spurious double-kick is benign (producer runs once
    /// more with little work to do).
    pub producer_pending: AtomicBool,
    /// Number of times `Engine::producer_step` has entered. Replaces the
    /// pre-emission-rewrite `Engine::tick_counter` diagnostic; host
    /// telemetry plots this as the producer heartbeat.
    pub producer_runs_total: AtomicU64,
    /// Per-motor consumer step-pulse counter. Matches `stepper_counts`
    /// cumulatively; surfaced as a sanity-check that the consumer is
    /// firing the entries the producer pushed.
    pub consumer_pulses_total: [AtomicU64; 4],
    /// Per-motor consumer underrun count. Bumped when the per-stepper
    /// consumer timer wakes up to find its ring empty (the poll-cadence
    /// fallback in spec §3.5). A non-zero value means the producer is
    /// falling behind for that motor — either insufficient ring depth
    /// at the natural step rate or a foreground stall hiding kicks.
    pub consumer_underrun_total: [AtomicU64; 4],
    /// Per-motor peak `available` ever observed in the StepRing. Surfaces
    /// how close we are to ring-full back-pressure during steady state.
    pub ring_high_water: [AtomicU32; 4],
    /// Total successful `ring.push` calls across all motors in
    /// `Engine::producer_step`. If `producer_runs_total` is growing but
    /// this stays at 0, the producer is running but every motor either
    /// hits SegmentExhausted on first Cardano call OR `fetch_segment_for_motor`
    /// returns None.
    pub producer_steps_pushed_total: AtomicU64,
    /// Total times `compute_next_step_time` returned `SegmentExhausted` in
    /// `Engine::producer_step` (per motor, summed across motors). Tells us
    /// whether Cardano is finding zero roots immediately.
    pub producer_motor_finished_curve_total: AtomicU64,
    /// Total times a full segment was retired (all consumers_remaining
    /// bits cleared) by `Engine::producer_step`. Increments once per
    /// dequeued+retired segment.
    pub producer_segment_retired_total: AtomicU64,
    /// 2026-05-21 bench diag — per-stage isr_sample_tick cycle costs.
    /// Each holds the running MAX cycle count for that stage of
    /// `runtime::tick::isr_sample_tick`. Read by the
    /// runtime_status_drain rotation as tags 0xE6/0xE7/0xE8. If any
    /// stage's max approaches the TIM5 period (~13000 cycles at 40 kHz
    /// on H7), that's the section starving foreground.
    /// `isr_overrun_count` increments per ISR that exceeds 30000 cycles
    /// (~58 µs) of total body time — that's the circuit-breaker signal.
    pub isr_widen_cycles_max: AtomicU32,
    pub isr_arm_cycles_max: AtomicU32,
    pub isr_eval_cycles_max: AtomicU32,
    pub isr_overrun_count: AtomicU32,
    /// Decision-path counters in isr_sample_tick's dequeue/park/arm block.
    /// Tell us exactly WHICH branch the ISR takes for every candidate.
    pub isr_deq_some_count: AtomicU32,
    pub isr_deq_none_count: AtomicU32,
    pub isr_parked_count: AtomicU32,
    pub isr_armed_count: AtomicU32,
    /// Last observed comparands at the most-recent park/arm decision.
    /// If isr_parked_count > 0, `isr_last_t_start_lo > isr_last_widened_lo`
    /// (in their low-32 domain) is the actual park reason.
    pub isr_last_t_start_lo: AtomicU32,
    pub isr_last_widened_lo: AtomicU32,
    /// 2026-05-21 epoch-diagnosis diag: HIGH 32 bits of seg.t_start and
    /// widened_now at the most-recent park/arm decision, plus lo/hi of the
    /// signed cycle-delta (now - t_start) as saturating_sub.
    /// These four expose whether hypothesis (a) or (b) is the root cause:
    ///   (a) t_start is in a wrong epoch (e.g., host sent seconds×freq rather
    ///       than MCU-native DWT cycles): both _hi would be non-zero but wildly
    ///       different magnitudes.
    ///   (b) t_start was narrowed to u32 on the wire or in C-side decode:
    ///       isr_last_t_start_hi would be 0 while isr_last_widened_hi would be
    ///       non-zero (MCU has been up > 8.3 s → high bits accumulated).
    pub isr_last_t_start_hi: AtomicU32,
    pub isr_last_widened_hi: AtomicU32,
    /// Low / high 32 bits of `now.saturating_sub(seg.t_start)` captured at the
    /// same park/arm decision. If this is ≈ uptime×clock_freq (e.g., 32 s ×
    /// 520 MHz = 16.6 G cycles), t_start was 0 or in the wrong epoch.
    pub isr_arm_delta_lo: AtomicU32,
    pub isr_arm_delta_hi: AtomicU32,
    /// Bit-pattern of the last `p_end` value passed to dispatch_pulse
    /// when the overflow guard tripped. f32::to_bits stored verbatim;
    /// host decodes via f32::from_bits(...) for the actual magnitude.
    pub isr_last_p_end_bits: AtomicU32,
    /// Bit-pattern of `microstep_distance` from the same call. Same
    /// encoding rationale.
    pub isr_last_microstep_bits: AtomicU32,
    /// `piece.coeffs[0]` (c0) bits from the active piece at the same
    /// instant. ~90mm if the curve_pool slot is loaded correctly.
    pub isr_last_c0_bits: AtomicU32,
    /// `t_local` (sec since piece start) bits. If huge, the time-domain
    /// mapping between seg.t_start (cycles) and widened_now (cycles) is
    /// broken or the duration is wrongly tiny.
    pub isr_last_t_local_bits: AtomicU32,
    /// Total step entries successfully pushed via queue_push across all
    /// dispatch_pulse calls. If this stays 0 while EA/ED bump, then
    /// `dispatch_pulse` is early-returning at `signed_steps == 0` —
    /// the eval isn't producing enough p_end change to cross microstep
    /// thresholds. If non-zero while motors stay silent, the per-axis
    /// timer or runtime_emit_step_pulses GPIO toggle is broken.
    pub isr_step_push_count: AtomicU32,
    /// Last non-zero `signed_steps` value (i.e., last actual step demand)
    /// in `dispatch_pulse`. Stays at 0 if no sample ever produced a
    /// non-zero step demand.
    pub isr_last_signed_steps: AtomicU32,
    /// Pulse-path branch diagnostics. These distinguish "never entered
    /// Pulse dispatch" from "entered but every sample had zero demand" and
    /// from "configuration made microstep_distance invalid".
    pub isr_pulse_call_count: AtomicU32,
    pub isr_pulse_zero_step_count: AtomicU32,
    pub isr_pulse_bad_mstep_count: AtomicU32,
    pub isr_phase_call_count: AtomicU32,
    /// Packed `(axis_idx << 16) | raw_mode_byte` from the most recent
    /// dispatch_axis call.
    pub isr_last_axis_mode_packed: AtomicU32,
    /// Packed `(target_step_count low16 << 16) | prev_step_count low16`
    /// from the most recent Pulse dispatch.
    pub isr_last_step_counts_packed: AtomicU32,
    /// 2026-05-21 arm-time diagnostic: raw packed `seg.x_handle` of the
    /// most recently armed segment. 0xFFFE_FFFE = UNUSED_SENTINEL (bridge
    /// did not associate an X curve). Other values mean bridge sent a
    /// real handle.
    pub isr_last_arm_x_handle: AtomicU32,
    /// 2026-05-21 arm-time diagnostic: outcome of arm for X axis.
    /// 0 = never armed, 1 = UNUSED handle, 2 = lookup_active returned
    /// None (slot/gen mismatch), 3 = curve loaded but piece_count==0,
    /// 4 = OK (axis.piece set to Some). Tells us which of the three
    /// "axis.piece becomes None" funnel paths actually fired.
    pub isr_last_arm_x_outcome: AtomicU32,
    /// 2026-05-21 arm-time diagnostic: piece_count of the X curve at arm
    /// time (only meaningful when outcome >= 3). 0 confirms the
    /// piece_count==0 branch fired; >0 + outcome=4 means arm succeeded
    /// and the failure is downstream (advance_piece_if_needed walking
    /// past exhaustion is the prime remaining suspect).
    pub isr_last_arm_x_piece_count: AtomicU32,
    /// 2026-05-21 arm-time diagnostic: `participating_mask` snapshot at
    /// end of arm. Bit 0 = A/X, bit 1 = B/Y, bit 2 = Z, bit 3 = E. If 0,
    /// no axes participated → instant retire (matches observed "ghost
    /// retire" symptom).
    pub isr_last_arm_participating: AtomicU32,
    /// 2026-05-21 arm-time: f32-bits of `pieces[0].duration` for the X
    /// curve at arm. If 0 (= 0.0 seconds), `bernstein_to_monomial_with_duration`
    /// divides coeffs by 0 → inf/NaN → Bezier eval returns NaN → signed_steps=0.
    /// Wire-side defect: load_curve sent duration_bits=0 or `populate_from_wire`
    /// converted incorrectly.
    pub isr_last_arm_x_piece0_duration_bits: AtomicU32,
    /// 2026-05-18 wedge diag: incremented in `producer_step` every time the
    /// `producer_current.is_none()` branch is entered, regardless of whether
    /// the subsequent `queue.dequeue()` returned Some or None. Cross-check
    /// with `producer_segment_dequeued_total`:
    ///   observed_none == dequeued → ISR not setting producer_current=None
    ///                                after retire (sticky-Some).
    ///   observed_none >> dequeued → queue.dequeue() returns None despite
    ///                                queue having entries (SPSC bug).
    pub producer_observed_none_total: AtomicU64,
    /// 2026-05-18 wedge diag: latest `queue.len()` snapshot from producer_step's
    /// perspective. Compare with `kalico_runtime_queue_len_diag` (called from
    /// status_drain at a different time / via &IsrState borrow) to detect if
    /// the SPSC Consumer's view of head/tail diverges between call sites.
    pub producer_step_last_len_snapshot: AtomicU32,
    /// 2026-05-18 wedge diag: producer_step's OWN view of
    /// `engine.producer_current.is_some()` (0/1). Written at the entry to
    /// producer_step on every call. Compare with status_drain's
    /// kalico_runtime_producer_current_is_some_diag (read via a different
    /// borrow path). If they disagree, producer_current is being read
    /// inconsistently between call sites (compiler caching a non-atomic
    /// field across function boundaries despite the field changing
    /// in-between).
    pub producer_step_current_is_some_snapshot: AtomicU8,
    /// 2026-05-18 wedge fix: atomic gate flag for `engine.producer_current`.
    /// Mirrors `producer_current.is_some()` but is atomic-readable across
    /// the &mut Engine borrow boundary. The non-atomic Option<Segment>
    /// field gets cached by the compiler under LTO; reads of THIS atomic
    /// can't be cached and force a fresh memory access. Used by
    /// `producer_step` as the gate for "should I dequeue?" instead of
    /// `self.producer_current.is_none()`.
    pub producer_current_present: AtomicBool,
    /// Total times `Engine::fetch_segment_for_motor` was called. Bumps
    /// unconditionally at function entry — distinguishes "producer loop
    /// is filtering out all motors at the gates" from "fetch is called
    /// but queue.dequeue always returns None".
    pub producer_fetch_attempts_total: AtomicU64,
    /// Total times `push_segment_impl` reached its successful enqueue.
    /// Bumps AFTER `fg.queue_producer.enqueue(seg)` returns Ok. If this
    /// is non-zero while `producer_segment_dequeued_total` is 0, the
    /// queue's enqueue/dequeue ends aren't sharing the backing buffer.
    pub producer_enqueue_success_total: AtomicU64,
    /// Last result code returned from `push_segment_impl`. 0 = KALICO_OK,
    /// negative = an error path (see error.rs constants). Set on every
    /// call so the C-side diag can show which rejection path is firing.
    pub last_push_segment_result: AtomicI32,
    /// Count of times `pool.resolve(primary)` returned `Some` in
    /// `Engine::producer_step` (i.e. the primary curve handle was valid
    /// and the slot's generation matched). Cross-check against
    /// `producer_fetch_attempts_total`: if the latter is non-zero but
    /// this is 0, every primary handle is either UNUSED or the slot's
    /// generation has been retired without a matching reload.
    pub producer_primary_resolved_total: AtomicU64,
    /// Count of times `pool.resolve(primary)` returned `None` AND the
    /// handle was NOT the UNUSED sentinel. Distinguishes "host sent
    /// a real handle but the pool no longer has it" from "host sent
    /// UNUSED on purpose."
    pub producer_primary_stale_total: AtomicU64,
    /// Count of times `primary.is_unused_sentinel()` was true. The
    /// natural case for a stationary-axis segment.
    pub producer_primary_unused_total: AtomicU64,
    /// 2026-05-15 live diagnosis: count of `push_segment_impl` calls
    /// where the computed `consumers_remaining` mask is zero (i.e. every
    /// handle was UNUSED). Such segments retire on the producer's very
    /// first dequeue without ever invoking the motor processing path.
    /// If this counter advances during a jog, the bridge is sending
    /// no-handle segments to the MCU.
    pub push_segment_all_unused_total: AtomicU64,
    /// Last `x_handle.pack()` value observed by `push_segment_impl`. Used
    /// only for live diagnosis; not part of any production invariant.
    pub last_push_x_handle_packed: AtomicU32,
    /// Last `y_handle.pack()` value observed by `push_segment_impl`.
    pub last_push_y_handle_packed: AtomicU32,
    /// Last `consumers_remaining` mask computed by `push_segment_impl`.
    pub last_push_consumers_remaining: AtomicU32,
    /// 2026-05-15 live diagnosis (CP capture): cps[0] (start control
    /// point, mm) of the last resolved primary X curve, raw f32 bits.
    /// Captured in producer_step right after `pool.resolve(primary)`
    /// returns Some. For a 0.5 mm X jog starting at X=125.0, this should
    /// be 125.0 (= 0x42FA0000). If the bits look corrupted or constant,
    /// the curve_pool's slot contents have been corrupted on the wire.
    pub last_resolved_primary_cps_0: AtomicU32,
    /// Last resolved primary X curve's cps[3] (end control point, mm),
    /// raw f32 bits. For a 0.5 mm X jog starting at X=125.0, this should
    /// be 125.5 (= 0x42FB0000). Compare with cps_0 — if they match, the
    /// curve has zero displacement and the producer correctly returns
    /// `SegmentExhausted` (which would indicate a planner-side bug, not
    /// MCU corruption).
    pub last_resolved_primary_cps_3: AtomicU32,
    /// CoreXY-combined cps[0] after `kine.combine` for motor A
    /// (A = X + Y). f32 bits. Compare with last_resolved_primary_cps_0
    /// to detect kinematic-mixing bugs (e.g. Y curve resolves to a
    /// non-constant when it should be constant for a pure-X jog).
    pub last_combined_motor_a_cps_0: AtomicU32,
    /// CoreXY-combined cps[3] after `kine.combine` for motor A. f32 bits.
    pub last_combined_motor_a_cps_3: AtomicU32,

    // Stepping-redesign telemetry (per 2026-05-19 design §10).
    /// Per-axis high-water mark for the per-axis step-event queue depth.
    /// ISR samples post-enqueue; foreground reads via the 10 Hz status frame.
    pub queue_high_water: [AtomicU32; 4],
    /// Per-axis count of `StepQueueOverflow` events. Bumps each time the
    /// per-axis queue refuses an enqueue. Cumulative — never decremented.
    pub queue_overflow_count: [AtomicU32; 4],
    /// Count of sample ticks in which the phase-stepping SPI bus saturated
    /// (a frame had to be dropped or coalesced because the DMA pipe was full).
    pub spi_saturated_samples: AtomicU32,
    /// Peak observed cycles spent inside the sample ISR, across all ticks
    /// since boot. Use the rdcyc / DWT-CYCCNT counter; never decreases.
    pub sample_isr_peak_cycles: AtomicU32,
    /// Peak observed cycles spent inside the per-axis consumer hook, indexed
    /// by axis. Used to spot a runaway axis-local hot path independently of
    /// the global `sample_isr_peak_cycles`.
    pub per_axis_consumer_peak_cycles: [AtomicU32; 4],

    // Stepping-redesign Task 10: scheduler tunables published by the
    // foreground config path; consumed by the per-axis timer.
    //
    // `dispatcher_floor_cycles` is the minimum cycles-into-future the
    // per-axis timer adds to `now` when computing its next waketime; it
    // prevents runaway re-entry when entries' `cycle_abs` values land in
    // the past.
    //
    // `sample_period_cycles` is the empty-queue poll cadence (typically the
    // sample-rate period — 25 µs at 40 kHz).
    //
    // Foreground sets both via `configure_kinematics` in Task 11. Until
    // then, 0 means "always reschedule for next sample without floor."
    pub dispatcher_floor_cycles: AtomicU32,
    pub sample_period_cycles: AtomicU32,

    // Stepping-redesign Task 12: ramp rate for `set_stepper_offset`.
    //
    // Published by the foreground command handler; consumed by the Task-13
    // ramp helper that walks `phase_offset_microsteps` toward
    // `phase_offset_target` at most `max_phase_offset_ramp_per_sample`
    // microsteps per sample. Validated `1..=256` at the command boundary.
    // `0` means "Task-13 helper not configured yet" — the helper treats
    // that as a hard skip (no ramp happens) so an unconfigured runtime
    // can't run away with a stale target.
    pub max_phase_offset_ramp_per_sample: AtomicU16,
}

impl SharedState {
    pub const fn new() -> Self {
        Self {
            last_error: AtomicI32::new(0),
            runtime_status: AtomicU8::new(crate::engine::RuntimeStatus::Idle as u8),
            stream_open: AtomicBool::new(false),
            force_idle: AtomicBool::new(false),
            acked_force_idle: AtomicBool::new(false),
            widened_now_lo: AtomicU32::new(0),
            widened_now_hi: AtomicU32::new(0),
            widened_now_seq: AtomicU32::new(0),
            sample_drop_pending: AtomicBool::new(false),
            last_modulated_elapsed_lo: AtomicU32::new(0),
            last_modulated_duration_lo: AtomicU32::new(0),
            modulated_retire_attempts: AtomicU32::new(0),
            modulated_retire_successes: AtomicU32::new(0),
            last_retire_consumers_after_clear: AtomicU32::new(0),
            fault_detail: AtomicU32::new(0),
            stepper_counts: [
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
            ],
            step_modes: [
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
            ],
            phase_config: [
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
            ],
            phase_slot_idx: [
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
            ],
            phase_motor_count: AtomicU8::new(0),
            producer_pending: AtomicBool::new(false),
            producer_runs_total: AtomicU64::new(0),
            consumer_pulses_total: [
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
            ],
            consumer_underrun_total: [
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
            ],
            ring_high_water: [
                AtomicU32::new(0),
                AtomicU32::new(0),
                AtomicU32::new(0),
                AtomicU32::new(0),
            ],
            producer_steps_pushed_total: AtomicU64::new(0),
            producer_motor_finished_curve_total: AtomicU64::new(0),
            producer_segment_retired_total: AtomicU64::new(0),
            isr_widen_cycles_max: AtomicU32::new(0),
            isr_arm_cycles_max: AtomicU32::new(0),
            isr_eval_cycles_max: AtomicU32::new(0),
            isr_overrun_count: AtomicU32::new(0),
            isr_deq_some_count: AtomicU32::new(0),
            isr_deq_none_count: AtomicU32::new(0),
            isr_parked_count: AtomicU32::new(0),
            isr_armed_count: AtomicU32::new(0),
            isr_last_t_start_lo: AtomicU32::new(0),
            isr_last_widened_lo: AtomicU32::new(0),
            isr_last_t_start_hi: AtomicU32::new(0),
            isr_last_widened_hi: AtomicU32::new(0),
            isr_arm_delta_lo: AtomicU32::new(0),
            isr_arm_delta_hi: AtomicU32::new(0),
            isr_last_p_end_bits: AtomicU32::new(0),
            isr_last_microstep_bits: AtomicU32::new(0),
            isr_last_c0_bits: AtomicU32::new(0),
            isr_last_t_local_bits: AtomicU32::new(0),
            isr_step_push_count: AtomicU32::new(0),
            isr_last_signed_steps: AtomicU32::new(0),
            isr_pulse_call_count: AtomicU32::new(0),
            isr_pulse_zero_step_count: AtomicU32::new(0),
            isr_pulse_bad_mstep_count: AtomicU32::new(0),
            isr_phase_call_count: AtomicU32::new(0),
            isr_last_axis_mode_packed: AtomicU32::new(0),
            isr_last_step_counts_packed: AtomicU32::new(0),
            isr_last_arm_x_handle: AtomicU32::new(0),
            isr_last_arm_x_outcome: AtomicU32::new(0),
            isr_last_arm_x_piece_count: AtomicU32::new(0),
            isr_last_arm_participating: AtomicU32::new(0),
            isr_last_arm_x_piece0_duration_bits: AtomicU32::new(0),
            producer_observed_none_total: AtomicU64::new(0),
            producer_step_last_len_snapshot: AtomicU32::new(0),
            producer_step_current_is_some_snapshot: AtomicU8::new(0),
            producer_current_present: AtomicBool::new(false),
            producer_fetch_attempts_total: AtomicU64::new(0),
            producer_enqueue_success_total: AtomicU64::new(0),
            last_push_segment_result: AtomicI32::new(0),
            producer_primary_resolved_total: AtomicU64::new(0),
            producer_primary_stale_total: AtomicU64::new(0),
            producer_primary_unused_total: AtomicU64::new(0),
            push_segment_all_unused_total: AtomicU64::new(0),
            last_push_x_handle_packed: AtomicU32::new(0),
            last_push_y_handle_packed: AtomicU32::new(0),
            last_push_consumers_remaining: AtomicU32::new(0),
            last_resolved_primary_cps_0: AtomicU32::new(0),
            last_resolved_primary_cps_3: AtomicU32::new(0),
            last_combined_motor_a_cps_0: AtomicU32::new(0),
            last_combined_motor_a_cps_3: AtomicU32::new(0),

            // Stepping-redesign telemetry (per 2026-05-19 design §10).
            // `AtomicU32` is not `Copy`, so `[AtomicU32::new(0); 4]` doesn't
            // compile. Use `[const { ... }; N]` (Rust 1.79+) for clean,
            // const-evaluable array initialization.
            queue_high_water: [const { AtomicU32::new(0) }; 4],
            queue_overflow_count: [const { AtomicU32::new(0) }; 4],
            spi_saturated_samples: AtomicU32::new(0),
            sample_isr_peak_cycles: AtomicU32::new(0),
            per_axis_consumer_peak_cycles: [const { AtomicU32::new(0) }; 4],

            // Stepping-redesign Task 10. Both 0 until Task 11 publishes
            // real values from configure_kinematics; 0 degrades safely
            // (no floor, immediate-resample empty-queue wake).
            dispatcher_floor_cycles: AtomicU32::new(0),
            sample_period_cycles: AtomicU32::new(0),

            // Task 12 ramp rate. `0` is "unconfigured"; Task 13's ramp
            // helper does nothing until a `set_stepper_offset` command
            // has validated and published a value in `1..=256`.
            max_phase_offset_ramp_per_sample: AtomicU16::new(0),
        }
    }
}

impl Default for SharedState {
    fn default() -> Self {
        Self::new()
    }
}

/// Step-6 half-split runtime context. Replaces Step-5's monolithic struct.
///
/// Layout invariants:
/// - `fg` and `isr` are `UnsafeCell<…>` so the FFI shim can project to either
///   half-state via `core::ptr::addr_of!` + `UnsafeCell::raw_get` without
///   ever materializing `&mut RuntimeContext`. Spec §11.2 closes the Step-5
///   latent UB by ensuring at most ONE `&mut FgState` OR `&mut IsrState`
///   (disjoint memory) exists at a time.
/// - `shared` is plain (no `UnsafeCell`); all writes go through atomics.
/// - `piece_storage` is the flat `[PieceEntry; TOTAL_RING_PIECES]` array that
///   all per-axis ring regions carve into. It is `UnsafeCell` so the ISR can
///   project a `&mut [PieceEntry]` slice through the `RuntimeContext` shared
///   reference while the foreground simultaneously holds `&mut FgState` — the
///   two borrows are to disjoint memory. The foreground writes via
///   `Engine::push_pieces`; the ISR reads/pops via `Engine::tick`. Mutual
///   exclusion is the same as the existing ISR/foreground discipline.
#[allow(missing_debug_implementations)] // Inner half-states wrap non-Debug types.
pub struct RuntimeContext {
    /// Foreground-only half. Reach via `addr_of!((*ctx).fg)` →
    /// `UnsafeCell::raw_get` → `&mut FgState`. Spec §11.2.
    pub fg: UnsafeCell<FgState>,
    /// ISR-only half. Same projection pattern as `fg`. Spec §11.2.
    pub isr: UnsafeCell<IsrState>,
    /// Cross-half atomics. Read/written through `&SharedState` (atomics
    /// supply the synchronization). Spec §11.3.
    pub shared: SharedState,
    /// Flat piece ring backing store.  Each axis gets a contiguous sub-region
    /// described by `AxisState::ring` (a `RingDescriptor` — offset + depth).
    /// `UnsafeCell` so the ISR can mutate (pop) while the foreground pushes
    /// into distinct ring regions without forming overlapping `&mut` borrows.
    ///
    /// C/Rust boundary: `piece_storage` lives inside the C-declared
    /// `rt_storage` buffer, so C owns linker-section placement on the MCU
    /// (docs/kalico-rewrite/mcu-c-rust-boundary.md rule B2). No additional
    /// `#[link_section]` is needed here.
    pub piece_storage: UnsafeCell<[PieceEntry; TOTAL_RING_PIECES]>,
}

// SAFETY: `UnsafeCell` is `!Sync` by default — we provide `Sync` for
// `RuntimeContext` because the FFI shim only ever forms shared `&` and
// projects to disjoint `&mut FgState` / `&mut IsrState` via raw pointers,
// never `&mut RuntimeContext`.
unsafe impl Sync for RuntimeContext {}

unsafe extern "C" {
    /// C-side static, set at `runtime_init` time in `src/runtime_tick.c`.
    static runtime_clock_freq: u32;
    /// TIM5 ISR fire rate (Hz). Defined in `src/runtime_tick.c` as
    /// `CONFIG_KALICO_MOTION_SAMPLE_RATE_HZ` (defaults: 40000 on H7,
    /// 20000 on F4, 10000 on Linux sim). Consumed here to publish
    /// `Engine::sample_period_sec` / `sample_period_cycles` at init time
    /// so `tick_sample`'s guard never fires in production.
    static runtime_sample_rate_hz: u32;
}

impl RuntimeContext {
    /// Initializes the runtime context in place at `rt_ptr`.
    ///
    /// SAFETY: the caller must guarantee single-threaded init before any FFI
    /// call hits the runtime (the FFI shim enforces this via a one-shot
    /// `AtomicBool` guard on `kalico_runtime_init`). This function writes
    /// through raw-pointer projections; it never materializes `&mut
    /// RuntimeContext` and is sound to call against `MaybeUninit::as_mut_ptr()`.
    pub unsafe fn init(rt_ptr: *mut RuntimeContext) {
        // SAFETY: caller guarantees `rt_ptr` is valid for writes and
        // exclusively-owned for the duration of init. We only form raw
        // pointers to fields and never a `&mut RuntimeContext`.
        unsafe {
            // Initialize SharedState.
            let shared_ptr = core::ptr::addr_of_mut!((*rt_ptr).shared);
            shared_ptr.write(SharedState::new());

            // Zero-initialize piece_storage (all entries start zeroed).
            // `UnsafeCell<[PieceEntry; N]>` is layout-compatible with `[PieceEntry; N]`
            // (`UnsafeCell` is `#[repr(transparent)]`).  Writing zeroes is safe
            // because `PieceEntry` is `#[repr(C)]` with no padding and all-zero is a
            // valid bit pattern (start_time=0, coeffs=0.0, duration=0.0).
            let ps_ptr = core::ptr::addr_of_mut!((*rt_ptr).piece_storage);
            core::ptr::write_bytes(
                ps_ptr.cast::<u8>(),
                0u8,
                core::mem::size_of::<UnsafeCell<[crate::piece_ring::PieceEntry; TOTAL_RING_PIECES]>>(
                ),
            );

            // Read C-side clock frequency and sample rate once so the ISR's
            // WidenState + Engine::init_in_place_production both see the same
            // values. Both constants are set at static-init time in
            // `src/runtime_tick.c` before the runtime ever runs.
            let freq = core::ptr::read_volatile(core::ptr::addr_of!(runtime_clock_freq));
            let sample_rate_hz =
                core::ptr::read_volatile(core::ptr::addr_of!(runtime_sample_rate_hz));

            // Stepping-redesign Task 10 / Codex M4 (2026-05-20): publish the
            // scheduler tunables to `SharedState` so the per-axis Klipper
            // timer's empty-queue rescheduling math uses the real sample-period
            // cadence (typically 25 µs at 40 kHz on H7) instead of the
            // `0 → waketime = now` fallback that pegged the foreground
            // scheduler.
            let sample_period_cycles_init: u32 = if sample_rate_hz == 0 {
                0
            } else {
                (freq + sample_rate_hz / 2) / sample_rate_hz
            };
            let dispatcher_floor_cycles_init: u32 = freq / 1_000_000;
            let shared_ref: *const SharedState = core::ptr::addr_of!((*rt_ptr).shared);
            (*shared_ref).sample_period_cycles.store(
                sample_period_cycles_init,
                core::sync::atomic::Ordering::Release,
            );
            (*shared_ref).dispatcher_floor_cycles.store(
                dispatcher_floor_cycles_init,
                core::sync::atomic::Ordering::Release,
            );

            // Initialize FgState.
            let fg_ptr = core::ptr::addr_of_mut!((*rt_ptr).fg);
            fg_ptr.write(UnsafeCell::new(FgState {
                current_stream_id: None,
                armed_t_start_t0: None,
                flush_start_tick: None,
            }));

            // Initialize IsrState — IN-PLACE, field-by-field, to avoid
            // materializing the multi-KB `EngineImpl` on the 8 KB MCU stack.
            let isr_ptr = core::ptr::addr_of_mut!((*rt_ptr).isr);
            let inner_ptr: *mut IsrState = UnsafeCell::raw_get(isr_ptr);
            EngineImpl::init_in_place_production(
                core::ptr::addr_of_mut!((*inner_ptr).engine),
                freq,
                sample_rate_hz,
            );
            core::ptr::addr_of_mut!((*inner_ptr).widen_state).write(WidenState::default());
            core::ptr::addr_of_mut!((*inner_ptr).last_tick_now).write(None);
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SetStepModeError {
    /// Requested `StepMode::Modulated` on an MCU whose capability bitmap
    /// does not advertise `PHASE_STEPPING`. Spec §4.
    CapabilityMissing,
    /// `stepper_idx >= MAX_STEPPER_OIDS`.
    OutOfRange,
}

/// Atomically flip a stepper's `StepMode`. Enforces the capability
/// ceiling: `Modulated` is rejected if the MCU doesn't advertise the
/// phase-stepping bit. Spec §10.
///
/// `Release` ordering on the store pairs with `Acquire` loads in the
/// engine ISR and any foreground reader of `step_modes`.
pub fn set_step_mode(
    shared: &SharedState,
    stepper_idx: u8,
    mode: StepMode,
    mcu_supports_phase: bool,
) -> Result<(), SetStepModeError> {
    if (stepper_idx as usize) >= MAX_STEPPER_OIDS {
        return Err(SetStepModeError::OutOfRange);
    }
    if mode == StepMode::Modulated && !mcu_supports_phase {
        return Err(SetStepModeError::CapabilityMissing);
    }
    shared.step_modes[stepper_idx as usize]
        .store(mode as u8, core::sync::atomic::Ordering::Release);
    Ok(())
}

#[cfg(test)]
mod size_task18;

#[cfg(test)]
mod tests;
