//! Half-split runtime state.
//!
//! `FgState` is touched only from foreground command-dispatch.
//! `IsrState` is touched only from the TIM5 ISR.
//! `SharedState` is touched concurrently from both via atomics only.
//!
//! Discipline contract: code-review-enforced. No compiler check. The TIM5
//! ISR is the SOLE writer of `IsrState`; any other interrupt that needs MCU
//! state goes through `SharedState` atomics.
//!
//! `TickState` is the per-tick struct shared with the PA/IS slot pipeline
//! and predates the half-split — it stays in this module.

// The half-split FFI projection (see `init` below) needs raw-pointer writes
// through `MaybeUninit` and an `unsafe impl Sync` for `RuntimeContext`; the
// foreign symbol declarations for `runtime_clock_freq` / `irq_save` /
// `irq_restore` also require `unsafe extern "C"`. Workspace lints deny
// `unsafe_code` globally — this module opts out with the rationale documented
// inline.
#![allow(unsafe_code)]

use core::cell::UnsafeCell;
// All atomic types come from `portable-atomic` rather than `core::sync::atomic`.
//
// Reason: `core::sync::atomic` does not provide RMW operations (fetch_add,
// compare_exchange, swap) on ARMv6-M (thumbv6m-none-eabi / STM32G0), because
// that architecture has no LDREX/STREX instructions. `portable_atomic` fills
// the gap: on thumbv7em it lowers to the native exclusive-monitor instructions
// (identical codegen, zero overhead); on thumbv6m it uses brief
// interrupt-disable critical sections (sound — single core, per the
// `portable_atomic_unsafe_assume_single_core` rustflag in .cargo/config.toml).
//
// `Ordering` and `fence` remain from `core::sync::atomic` — they are the same
// types `portable_atomic` accepts, so no call-site changes are needed.
use portable_atomic::{AtomicBool, AtomicI32, AtomicU8, AtomicU16, AtomicU32, AtomicU64};

use crate::clock::WidenState;
use crate::engine::Engine;
use crate::piece_ring::PieceEntry;

/// Runtime storage size — the byte count the C side must reserve for
/// `RuntimeContext`. Generated by `runtime/build.rs` into `$OUT_DIR/sizing.rs`.
/// Use `runtime::RT_STORAGE_SIZE` in external crates.
pub use crate::sizing::RT_STORAGE_SIZE;

/// Total number of piece entries in the shared ring storage.
/// Derived from `PIECE_RING_SIZE / 32` (each entry is 32 bytes).
pub use crate::sizing::TOTAL_RING_PIECES;

/// Byte size of the piece ring storage (compile-time constant from build.rs).
pub use crate::sizing::PIECE_RING_SIZE;

/// Per-stepper stepping-output strategy. Stored as `AtomicU8` in
/// `SharedState::step_modes`; runtime-mutable via `runtime_set_step_mode`.
///
/// Spec: docs/superpowers/specs/2026-05-12-step-time-scheduling-design.md §3.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum StepMode {
    /// Driven by TIM5 ISR at the MCU's modulation rate. Current behavior
    /// (polled curve eval + `StepAccumulator`). Future: grows to include
    /// sin/cos commutation per build-order Step 10.
    Modulated = 0,
    /// Driven by per-stepper Klipper `struct timer`. Engine computes each
    /// step's firing time via Newton iteration on the position polynomial.
    /// Default for all steppers; mandatory on MCUs that don't advertise
    /// the `PHASE_STEPPING` capability bit.
    StepTime = 1,
}

impl StepMode {
    pub fn from_u8(raw: u8) -> Option<StepMode> {
        match raw {
            0 => Some(StepMode::Modulated),
            1 => Some(StepMode::StepTime),
            _ => None,
        }
    }
}

/// Per-MCU stepper oid counter slots for homing snapshots and the
/// phase-stepping per-motor (bus_id, cs_pin_id, slot_idx) table.
///
/// 16 entries support a CoreXY+AWD (4 phase-stepped motors), full-Cartesian
/// (4 motors with no AWD), and headroom for N-motor-per-slot industrial
/// configurations up to a hard cap of 16 phase-stepped motors per MCU.
/// Memory cost is modest: each entry adds 1 (`AtomicU8` phase_slot_idx) +
/// 2 (`AtomicU16` phase_config) + 4 (`AtomicI32` stepper_counts) +
/// 1 (`AtomicU8` step_modes) ≈ 8 bytes; bumping 8 → 16 costs ~64 bytes.
pub const MAX_STEPPER_OIDS: usize = 16;

/// Per-tick state shared with PA/IS slots. Spec §3.1.
#[derive(Debug, Clone, Copy)]
pub struct TickState {
    pub dt: f32,
    pub positions: [f32; 4], // [x, y, z, e] logical
    pub motors: [f32; 4],    // [a, b, z, e] or [x, y, z, e] post-kinematic
}

/// Production `Engine` type alias. Kept so all existing call sites
/// (`IsrState::engine`, `init`, FFI) compile without annotation changes.
pub type EngineImpl = Engine;

// `force_idle` handshake calls Klipper's `irq_save`/`irq_restore` to gate
// the queue-drain step. We import via thin C wrappers `runtime_irq_save` /
// `runtime_irq_restore` defined in `src/runtime_tick.c`, not the bare
// functions directly: Klipper's MCU build uses `-flto=auto -fwhole-program`,
// which lets the LTO inliner DCE the standalone `irq_save` / `irq_restore`
// symbols (their bodies get inlined at every Klipper callsite) — leaving the
// kalico staticlib's references unresolvable at the final link. The wrappers
// are marked `used + externally_visible` on the C side so LTO keeps them.
unsafe extern "C" {
    pub fn runtime_irq_save() -> u32;
    pub fn runtime_irq_restore(flags: u32);
}

/// Foreground-only state. Touched exclusively by the command-dispatch task.
#[derive(Debug)]
pub struct FgState {
    /// Stream-open identity for idempotency (same-`stream_id` rule).
    pub current_stream_id: Option<u32>,
    /// Arm-time idempotency (arm with same `t_start_t0` returns OK).
    pub armed_t_start_t0: Option<u64>,
    /// Flush spin-wait deadline.
    pub flush_start_tick: Option<u64>,
}

/// ISR-half state. Written exclusively by the TIM5 ISR
/// (`kalico_runtime_tick_sample`). Mutual exclusion is enforced by
/// Cortex-M NVIC priority arbitration.
#[allow(missing_debug_implementations)] // Engine doesn't implement Debug.
#[repr(C)]
pub struct IsrState {
    pub engine: EngineImpl,
    /// CYCCNT widening. The ISR is the sole writer; foreground must not call
    /// `widen()` directly.
    pub widen_state: WidenState,
    /// Widened `now` from the previous `isr_sample_tick` call.
    /// `None` until the first active tick; idle ticks clear it to `None` so
    /// the inter-arrival guard never fires during boot/config.
    pub last_tick_now: Option<u64>,
}

impl IsrState {
    /// Return a raw const pointer to the `IsrState` inside `ctx`.
    ///
    /// Used by `engine::arm_step_timer_for_stepper` to form a shared reference
    /// to the ISR-owned engine and curve-pool state without taking `&mut
    /// IsrState`. The caller is responsible for the aliasing discipline (see
    /// the function's SAFETY doc).
    pub fn raw_ref_from_ctx(ctx: &RuntimeContext) -> *const Self {
        // `addr_of!` does not form a reference; `raw_get` returns a raw
        // pointer from the UnsafeCell without any unsafe operation.
        // The caller is responsible for upholding the non-exclusive borrow
        // invariant when it dereferences the returned pointer.
        core::cell::UnsafeCell::raw_get(core::ptr::addr_of!(ctx.isr))
    }
}

/// Cross-half shared state. Atomics only; no `&mut` reaches this struct.
#[derive(Debug)]
#[repr(C)]
pub struct SharedState {
    pub last_error: AtomicI32,
    pub runtime_status: AtomicU8,
    pub stream_open: AtomicBool,
    /// Foreground sets `force_idle` first, ack-waits, then clears
    /// `stream_open` (flush handshake decision A).
    pub force_idle: AtomicBool,
    pub acked_force_idle: AtomicBool,
    /// §11.4 widened-clock seqlock — foreground reads, ISR writes.
    pub widened_now_lo: AtomicU32,
    pub widened_now_hi: AtomicU32,
    pub widened_now_seq: AtomicU32,
    pub sample_drop_pending: AtomicBool,
    /// fault_detail 0xFB: low 32 bits of `now - seg.t_start` inside
    /// `runtime_modulated_tick`. If stuck at 0, the clock is behind
    /// `seg.t_start` and the `elapsed >= duration` retirement check can't fire.
    pub last_modulated_elapsed_lo: AtomicU32,
    /// fault_detail 0xFC: companion to `last_modulated_elapsed_lo`.
    /// `0xFB >= 0xFC` means retirement should fire on the next tick.
    pub last_modulated_duration_lo: AtomicU32,
    /// Increments on every entry into the `elapsed >= duration` retirement
    /// branch of `runtime_modulated_tick`.
    pub modulated_retire_attempts: AtomicU32,
    /// Increments on every successful retirement (`consumers_done == true`).
    /// Should equal `modulated_retire_attempts` when the consumers mask clears correctly.
    pub modulated_retire_successes: AtomicU32,
    /// Snapshot of `seg.consumers_remaining` after the clear-all-motors loop
    /// in `modulated_tick`'s retirement branch. Non-zero means the clear loop
    /// missed bits — remaining bits identify which positions need investigation.
    pub last_retire_consumers_after_clear: AtomicU32,
    /// §9.2 + §5.3 — last latched fault's encoded `fault_detail` payload.
    /// Set in lockstep with `last_error`. `0` when no fault has latched or
    /// when the fault carries no per-event detail.
    pub fault_detail: AtomicU32,
    /// Most-recently-dispatched scheduler timer func at `-311` fault time.
    /// Unreliable as a blocker signal — `tick_blocker_pc` is the primary
    /// `addr2line` target. `0` until `-311`.
    pub tick_blocker_func: AtomicU32,
    /// Stacked exception-frame PC at TIM5 handler entry, captured on the
    /// `-311` path. Surfaced via the fault event's `segment_id` field.
    /// `0` until `-311`.
    pub tick_blocker_pc: AtomicU32,
    /// Stacked xPSR exception number at `-311` time (`xPSR & 0x1FF`).
    /// `0` = foreground was interrupted; nonzero = that IRQ overran into TIM5.
    pub tick_blocker_exc: AtomicU32,
    /// Signed per-stepper pulse counters, indexed by stepper oid.
    pub stepper_counts: [AtomicI32; MAX_STEPPER_OIDS],
    /// Per-stepper `StepMode` (spec §5). Atomic so the host can flip a
    /// stepper between Modulated and StepTime at runtime (needed for future
    /// sensorless homing on phase-stepped axes — TMC StallGuard requires
    /// the driver's internal sequencer, which the direct/phase-stepping
    /// path bypasses). Default `StepTime` (enum value 1).
    pub step_modes: [AtomicU8; MAX_STEPPER_OIDS],
    /// Per-motor phase-stepping SPI config. Packed (`spi_bus_id << 8 |
    /// cs_pin_id`). `0xFFFF` means "no phase config — use the StepPulse
    /// output path." Populated during axis configuration; read by
    /// `runtime_modulated_tick`. See `crate::phase_config` for the helpers.
    ///
    /// In the variable-length layout (≥26-byte body), entry `motor_idx`
    /// describes the SPI bus / CS pin for the physical motor at
    /// `motor_idx`. The kinematic slot whose commanded `motors[slot_idx]`
    /// position drives this motor's XDIRECT output is in
    /// `phase_slot_idx[motor_idx]`. Multiple motors may share a slot
    /// (AWD pairs, N-motor-per-axis industrial configs).
    pub phase_config: [AtomicU16; MAX_STEPPER_OIDS],
    /// Per-motor kinematic-slot mapping. `phase_slot_idx[motor_idx]` is
    /// the slot whose commanded `motors[slot_idx]` position drives motor
    /// `motor_idx`'s XDIRECT output. Multiple motors can share a slot
    /// (AWD pairs, or industrial multi-motor-per-axis configs).
    /// Populated during axis configuration alongside `phase_config`.
    /// Unused entries hold `0xFF`.
    pub phase_slot_idx: [AtomicU8; MAX_STEPPER_OIDS],
    /// Number of valid entries in `phase_config` / `phase_slot_idx`. The
    /// ISR loops `0..phase_motor_count` rather than scanning the full
    /// `MAX_STEPPER_OIDS` array. `0` disables phase stepping on this MCU.
    pub phase_motor_count: AtomicU8,

    /// Dedupe flag for producer-timer kicks. Kickers CAS-set `false→true`;
    /// the CAS-winner schedules the producer struct timer. Producer clears
    /// on entry. A spurious double-kick is benign.
    pub producer_pending: AtomicBool,
    /// Count of `Engine::producer_step` entries (producer heartbeat).
    pub producer_runs_total: AtomicU64,
    /// Per-motor consumer step-pulse counter. Sanity-checks that the consumer
    /// fires the entries the producer pushed.
    pub consumer_pulses_total: [AtomicU64; 4],
    /// Per-motor consumer underrun count. Non-zero means the producer is
    /// falling behind for that motor.
    pub consumer_underrun_total: [AtomicU64; 4],
    /// Per-motor peak `available` ever observed in the StepRing. Shows how
    /// close we are to ring-full back-pressure during steady state.
    pub ring_high_water: [AtomicU32; 4],
    /// Total successful `ring.push` calls across all motors in
    /// `Engine::producer_step`. If `producer_runs_total` grows but this
    /// stays 0, the producer is running but every motor hits
    /// `SegmentExhausted` on first Cardano call OR `fetch_segment_for_motor`
    /// returns `None`.
    pub producer_steps_pushed_total: AtomicU64,
    /// Total times `compute_next_step_time` returned `SegmentExhausted`
    /// (per motor, summed across motors). Non-zero when Cardano finds zero
    /// roots immediately.
    pub producer_motor_finished_curve_total: AtomicU64,
    /// Total full-segment retirements in `Engine::producer_step`.
    pub producer_segment_retired_total: AtomicU64,
    /// Per-stage running MAX cycle counts for `runtime::tick::isr_sample_tick`.
    /// Read via status_drain rotation as tags 0xE6/0xE7/0xE8.
    /// If any stage approaches the TIM5 period (~13000 cycles at 40 kHz on H7),
    /// that stage is starving the foreground.
    pub isr_widen_cycles_max: AtomicU32,
    pub isr_arm_cycles_max: AtomicU32,
    pub isr_eval_cycles_max: AtomicU32,
    /// Increments per ISR that exceeds 30000 cycles (~58 µs) of total body
    /// time — circuit-breaker signal.
    pub isr_overrun_count: AtomicU32,
    /// Decision-path counters in `isr_sample_tick`'s dequeue/park/arm block.
    pub isr_deq_some_count: AtomicU32,
    pub isr_deq_none_count: AtomicU32,
    pub isr_parked_count: AtomicU32,
    pub isr_armed_count: AtomicU32,
    /// Comparands at the most-recent park/arm decision. If `isr_parked_count
    /// > 0`, `isr_last_t_start_lo > isr_last_widened_lo` is the actual park
    /// reason.
    pub isr_last_t_start_lo: AtomicU32,
    pub isr_last_widened_lo: AtomicU32,
    /// High 32 bits of `seg.t_start` and `widened_now` at the most-recent
    /// park/arm decision, plus lo/hi of `now.saturating_sub(seg.t_start)`.
    /// Distinguishes wrong-epoch t_start (both _hi non-zero but wildly
    /// different magnitudes) from narrowed-to-u32-on-wire t_start
    /// (`isr_last_t_start_hi == 0` while `isr_last_widened_hi != 0`).
    pub isr_last_t_start_hi: AtomicU32,
    pub isr_last_widened_hi: AtomicU32,
    /// Low / high 32 bits of `now.saturating_sub(seg.t_start)` at the
    /// same park/arm decision. If ≈ uptime×clock_freq, t_start was 0 or
    /// in the wrong epoch.
    pub isr_arm_delta_lo: AtomicU32,
    pub isr_arm_delta_hi: AtomicU32,
    /// f32-bits of `p_end` when the overflow guard tripped (decode via
    /// `f32::from_bits`).
    pub isr_last_p_end_bits: AtomicU32,
    /// f32-bits of `microstep_distance` from the same call.
    pub isr_last_microstep_bits: AtomicU32,
    /// f32-bits of `piece.coeffs[0]` (c0) at the same instant. ~90 mm if
    /// the curve_pool slot is loaded correctly.
    pub isr_last_c0_bits: AtomicU32,
    /// f32-bits of `t_local` (sec since piece start). If huge, the
    /// time-domain mapping between seg.t_start (cycles) and widened_now
    /// (cycles) is broken or duration is wrongly tiny.
    pub isr_last_t_local_bits: AtomicU32,
    /// Total step entries pushed via `queue_push` across all
    /// `dispatch_pulse` calls. If 0 while EA/ED bump, `dispatch_pulse` is
    /// early-returning at `signed_steps == 0`.
    pub isr_step_push_count: AtomicU32,
    /// Last non-zero `signed_steps` value in `dispatch_pulse`. `0` if no
    /// sample ever produced a non-zero step demand.
    pub isr_last_signed_steps: AtomicU32,
    /// Pulse-path branch diagnostics. Distinguish "never entered Pulse
    /// dispatch" from "entered but every sample had zero demand" and from
    /// "microstep_distance invalid."
    pub isr_pulse_call_count: AtomicU32,
    pub isr_pulse_zero_step_count: AtomicU32,
    pub isr_pulse_bad_mstep_count: AtomicU32,
    pub isr_phase_call_count: AtomicU32,
    /// Packed `(axis_idx << 16) | raw_mode_byte` from the most recent
    /// `dispatch_axis` call.
    pub isr_last_axis_mode_packed: AtomicU32,
    /// Packed `(target_step_count low16 << 16) | prev_step_count low16`
    /// from the most recent Pulse dispatch.
    pub isr_last_step_counts_packed: AtomicU32,
    /// Raw packed `seg.x_handle` of the most recently armed segment.
    /// `0xFFFE_FFFE` = UNUSED_SENTINEL (bridge sent no X curve).
    pub isr_last_arm_x_handle: AtomicU32,
    /// Outcome of arm for X axis: 0 = never armed, 1 = UNUSED handle,
    /// 2 = `lookup_active` returned None (slot/gen mismatch),
    /// 3 = curve loaded but `piece_count == 0`, 4 = OK.
    pub isr_last_arm_x_outcome: AtomicU32,
    /// `piece_count` of the X curve at arm time (meaningful when outcome ≥ 3).
    /// `0` confirms the `piece_count == 0` branch fired.
    pub isr_last_arm_x_piece_count: AtomicU32,
    /// `participating_mask` snapshot at end of arm.
    /// Bit 0 = A/X, 1 = B/Y, 2 = Z, 3 = E. If 0, no axes participated
    /// → instant retire ("ghost retire" symptom).
    pub isr_last_arm_participating: AtomicU32,
    /// f32-bits of `pieces[0].duration` for the X curve at arm. If 0
    /// (= 0.0 s), `bernstein_to_monomial_with_duration` divides by 0
    /// → inf/NaN → signed_steps=0. Indicates a wire-side defect in
    /// `load_curve` or `populate_from_wire`.
    pub isr_last_arm_x_piece0_duration_bits: AtomicU32,
    /// Incremented in `producer_step` every time `producer_current.is_none()`
    /// is entered, regardless of whether `queue.dequeue()` returned Some or None.
    /// Cross-check with `producer_segment_dequeued_total`:
    ///   `observed_none == dequeued` → ISR not clearing producer_current after retire.
    ///   `observed_none >> dequeued` → `queue.dequeue()` returns None despite entries (SPSC bug).
    pub producer_observed_none_total: AtomicU64,
    /// Latest `queue.len()` snapshot from `producer_step`'s perspective.
    pub producer_step_last_len_snapshot: AtomicU32,
    /// `producer_step`'s view of `engine.producer_current.is_some()` (0/1).
    /// Written at every `producer_step` entry.
    pub producer_step_current_is_some_snapshot: AtomicU8,
    /// Atomic mirror of `producer_current.is_some()`. The non-atomic
    /// `Option<Segment>` field can be cached by the compiler under LTO;
    /// reads of this atomic can't be cached and force a fresh memory access.
    /// Used by `producer_step` as the "should I dequeue?" gate.
    pub producer_current_present: AtomicBool,
    /// Total `Engine::fetch_segment_for_motor` calls. Bumps at function
    /// entry unconditionally — distinguishes "producer loop filters all
    /// motors" from "fetch called but queue.dequeue always returns None."
    pub producer_fetch_attempts_total: AtomicU64,
    /// Total times `push_segment_impl` reached its successful enqueue.
    /// Non-zero while `producer_segment_dequeued_total` is 0 → the queue's
    /// enqueue/dequeue ends aren't sharing the backing buffer.
    pub producer_enqueue_success_total: AtomicU64,
    /// Last result code from `push_segment_impl`. 0 = KALICO_OK, negative = error.
    pub last_push_segment_result: AtomicI32,
    /// Count of times `pool.resolve(primary)` returned `Some` in
    /// `Engine::producer_step`. If `producer_fetch_attempts_total` is non-zero
    /// but this is 0, every primary handle is UNUSED or the slot's generation
    /// has been retired without a matching reload.
    pub producer_primary_resolved_total: AtomicU64,
    /// Count of times `pool.resolve(primary)` returned `None` AND the handle
    /// was NOT the UNUSED sentinel. Distinguishes "host sent a real handle
    /// but the pool no longer has it" from "host sent UNUSED on purpose."
    pub producer_primary_stale_total: AtomicU64,
    /// Count of times `primary.is_unused_sentinel()` was true.
    pub producer_primary_unused_total: AtomicU64,
    /// Count of `push_segment_impl` calls where `consumers_remaining` is zero
    /// (every handle UNUSED). Such segments retire on the producer's first
    /// dequeue without touching the motor path. Non-zero during a jog means
    /// the bridge is sending no-handle segments.
    pub push_segment_all_unused_total: AtomicU64,
    /// Last `x_handle.pack()` observed by `push_segment_impl` (live diagnosis).
    pub last_push_x_handle_packed: AtomicU32,
    /// Last `y_handle.pack()` observed by `push_segment_impl`.
    pub last_push_y_handle_packed: AtomicU32,
    /// Last `consumers_remaining` mask computed by `push_segment_impl`.
    pub last_push_consumers_remaining: AtomicU32,
    /// `cps[0]` (start CP, mm) of the last resolved primary X curve, raw f32
    /// bits. For a 0.5 mm X jog at X=125.0 → `0x42FA0000`. Corrupted or
    /// constant bits indicate curve_pool slot corruption on the wire.
    pub last_resolved_primary_cps_0: AtomicU32,
    /// `cps[3]` (end CP, mm) of the last resolved primary X curve, raw f32
    /// bits. For a 0.5 mm X jog at X=125.0 → `0x42FB0000`. Matching `cps_0`
    /// means zero displacement — if so, `SegmentExhausted` on first call is
    /// correct and indicates a planner-side bug, not MCU corruption.
    pub last_resolved_primary_cps_3: AtomicU32,
    /// CoreXY-combined `cps[0]` after `kine.combine` for motor A (A = X + Y),
    /// f32 bits. Compare with `last_resolved_primary_cps_0` to detect kinematic-
    /// mixing bugs (e.g. Y resolves non-constant on a pure-X jog).
    pub last_combined_motor_a_cps_0: AtomicU32,
    /// CoreXY-combined `cps[3]` after `kine.combine` for motor A, f32 bits.
    pub last_combined_motor_a_cps_3: AtomicU32,

    /// Per-axis high-water mark for the per-axis step-event queue depth.
    /// ISR samples post-enqueue; foreground reads via the 10 Hz status frame.
    pub queue_high_water: [AtomicU32; 4],
    /// Per-axis count of `StepQueueOverflow` events. Cumulative.
    pub queue_overflow_count: [AtomicU32; 4],
    /// Count of sample ticks where the phase-stepping SPI bus saturated.
    pub spi_saturated_samples: AtomicU32,
    /// Peak cycles inside the sample ISR since boot. Never decreases.
    pub sample_isr_peak_cycles: AtomicU32,
    /// Peak cycles inside the per-axis consumer hook, indexed by axis.
    pub per_axis_consumer_peak_cycles: [AtomicU32; 4],

    /// Minimum cycles-into-future the per-axis timer adds to `now` when
    /// computing its next waketime; prevents runaway re-entry when entries'
    /// `cycle_abs` values land in the past. Published by `configure_kinematics`;
    /// `0` until then (no floor, immediate-resample on empty-queue wake).
    pub dispatcher_floor_cycles: AtomicU32,
    /// Empty-queue poll cadence in cycles (typically the sample-rate period —
    /// 25 µs at 40 kHz). Published by `configure_kinematics`; `0` until then.
    pub sample_period_cycles: AtomicU32,

    /// Ramp rate for `set_stepper_offset`. Published by the foreground command
    /// handler; consumed by the ramp helper that walks `phase_offset_microsteps`
    /// toward `phase_offset_target` at most this many microsteps per sample.
    /// Validated `1..=256` at the command boundary. `0` = unconfigured; ramp
    /// helper skips entirely to avoid running away with a stale target.
    pub max_phase_offset_ramp_per_sample: AtomicU16,
}

impl SharedState {
    pub const fn new() -> Self {
        Self {
            last_error: AtomicI32::new(0),
            runtime_status: AtomicU8::new(crate::engine::RuntimeStatus::Idle as u8),
            stream_open: AtomicBool::new(false),
            force_idle: AtomicBool::new(false),
            acked_force_idle: AtomicBool::new(false),
            widened_now_lo: AtomicU32::new(0),
            widened_now_hi: AtomicU32::new(0),
            widened_now_seq: AtomicU32::new(0),
            sample_drop_pending: AtomicBool::new(false),
            last_modulated_elapsed_lo: AtomicU32::new(0),
            last_modulated_duration_lo: AtomicU32::new(0),
            modulated_retire_attempts: AtomicU32::new(0),
            modulated_retire_successes: AtomicU32::new(0),
            last_retire_consumers_after_clear: AtomicU32::new(0),
            fault_detail: AtomicU32::new(0),
            tick_blocker_func: AtomicU32::new(0),
            tick_blocker_pc: AtomicU32::new(0),
            tick_blocker_exc: AtomicU32::new(0),
            stepper_counts: [
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
                AtomicI32::new(0),
            ],
            step_modes: [
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
                AtomicU8::new(StepMode::StepTime as u8),
            ],
            phase_config: [
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
                AtomicU16::new(crate::phase_config::NONE_SENTINEL),
            ],
            phase_slot_idx: [
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
                AtomicU8::new(0xFF),
            ],
            phase_motor_count: AtomicU8::new(0),
            producer_pending: AtomicBool::new(false),
            producer_runs_total: AtomicU64::new(0),
            consumer_pulses_total: [
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
            ],
            consumer_underrun_total: [
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
                AtomicU64::new(0),
            ],
            ring_high_water: [
                AtomicU32::new(0),
                AtomicU32::new(0),
                AtomicU32::new(0),
                AtomicU32::new(0),
            ],
            producer_steps_pushed_total: AtomicU64::new(0),
            producer_motor_finished_curve_total: AtomicU64::new(0),
            producer_segment_retired_total: AtomicU64::new(0),
            isr_widen_cycles_max: AtomicU32::new(0),
            isr_arm_cycles_max: AtomicU32::new(0),
            isr_eval_cycles_max: AtomicU32::new(0),
            isr_overrun_count: AtomicU32::new(0),
            isr_deq_some_count: AtomicU32::new(0),
            isr_deq_none_count: AtomicU32::new(0),
            isr_parked_count: AtomicU32::new(0),
            isr_armed_count: AtomicU32::new(0),
            isr_last_t_start_lo: AtomicU32::new(0),
            isr_last_widened_lo: AtomicU32::new(0),
            isr_last_t_start_hi: AtomicU32::new(0),
            isr_last_widened_hi: AtomicU32::new(0),
            isr_arm_delta_lo: AtomicU32::new(0),
            isr_arm_delta_hi: AtomicU32::new(0),
            isr_last_p_end_bits: AtomicU32::new(0),
            isr_last_microstep_bits: AtomicU32::new(0),
            isr_last_c0_bits: AtomicU32::new(0),
            isr_last_t_local_bits: AtomicU32::new(0),
            isr_step_push_count: AtomicU32::new(0),
            isr_last_signed_steps: AtomicU32::new(0),
            isr_pulse_call_count: AtomicU32::new(0),
            isr_pulse_zero_step_count: AtomicU32::new(0),
            isr_pulse_bad_mstep_count: AtomicU32::new(0),
            isr_phase_call_count: AtomicU32::new(0),
            isr_last_axis_mode_packed: AtomicU32::new(0),
            isr_last_step_counts_packed: AtomicU32::new(0),
            isr_last_arm_x_handle: AtomicU32::new(0),
            isr_last_arm_x_outcome: AtomicU32::new(0),
            isr_last_arm_x_piece_count: AtomicU32::new(0),
            isr_last_arm_participating: AtomicU32::new(0),
            isr_last_arm_x_piece0_duration_bits: AtomicU32::new(0),
            producer_observed_none_total: AtomicU64::new(0),
            producer_step_last_len_snapshot: AtomicU32::new(0),
            producer_step_current_is_some_snapshot: AtomicU8::new(0),
            producer_current_present: AtomicBool::new(false),
            producer_fetch_attempts_total: AtomicU64::new(0),
            producer_enqueue_success_total: AtomicU64::new(0),
            last_push_segment_result: AtomicI32::new(0),
            producer_primary_resolved_total: AtomicU64::new(0),
            producer_primary_stale_total: AtomicU64::new(0),
            producer_primary_unused_total: AtomicU64::new(0),
            push_segment_all_unused_total: AtomicU64::new(0),
            last_push_x_handle_packed: AtomicU32::new(0),
            last_push_y_handle_packed: AtomicU32::new(0),
            last_push_consumers_remaining: AtomicU32::new(0),
            last_resolved_primary_cps_0: AtomicU32::new(0),
            last_resolved_primary_cps_3: AtomicU32::new(0),
            last_combined_motor_a_cps_0: AtomicU32::new(0),
            last_combined_motor_a_cps_3: AtomicU32::new(0),

            // `AtomicU32` is not `Copy`, so `[AtomicU32::new(0); 4]` doesn't
            // compile. Use `[const { ... }; N]` (Rust 1.79+) for clean,
            // const-evaluable array initialization.
            queue_high_water: [const { AtomicU32::new(0) }; 4],
            queue_overflow_count: [const { AtomicU32::new(0) }; 4],
            spi_saturated_samples: AtomicU32::new(0),
            sample_isr_peak_cycles: AtomicU32::new(0),
            per_axis_consumer_peak_cycles: [const { AtomicU32::new(0) }; 4],

            dispatcher_floor_cycles: AtomicU32::new(0),
            sample_period_cycles: AtomicU32::new(0),

            max_phase_offset_ramp_per_sample: AtomicU16::new(0),
        }
    }
}

impl Default for SharedState {
    fn default() -> Self {
        Self::new()
    }
}

/// Half-split runtime context. `fg` and `isr` are disjoint memory regions
/// behind `UnsafeCell` so the FFI shim can project to either half via
/// `core::ptr::addr_of!` + `UnsafeCell::raw_get` without materializing
/// `&mut RuntimeContext`. At most ONE `&mut FgState` OR `&mut IsrState`
/// (disjoint memory) exists at a time. `shared` uses no `UnsafeCell` — all
/// writes go through atomics.
///
/// `piece_storage` is `UnsafeCell` so the ISR can project a `&mut
/// [PieceEntry]` slice while the foreground simultaneously holds `&mut
/// FgState` — the two borrows are to disjoint memory.
///
/// C/Rust boundary: `piece_storage` lives inside the C-declared `rt_storage`
/// buffer; C owns linker-section placement on the MCU
/// (docs/kalico-rewrite/mcu-c-rust-boundary.md rule B2). No additional
/// `#[link_section]` is needed here.
#[allow(missing_debug_implementations)] // Inner half-states wrap non-Debug types.
pub struct RuntimeContext {
    pub fg: UnsafeCell<FgState>,
    pub isr: UnsafeCell<IsrState>,
    pub shared: SharedState,
    pub piece_storage: UnsafeCell<[PieceEntry; TOTAL_RING_PIECES]>,
}

// SAFETY: `UnsafeCell` is `!Sync` by default — we provide `Sync` for
// `RuntimeContext` because the FFI shim only ever forms shared `&` and
// projects to disjoint `&mut FgState` / `&mut IsrState` via raw pointers,
// never `&mut RuntimeContext`.
unsafe impl Sync for RuntimeContext {}

unsafe extern "C" {
    /// C-side static, set at `runtime_init` time in `src/runtime_tick.c`.
    static runtime_clock_freq: u32;
    /// TIM5 ISR fire rate (Hz). Defined in `src/runtime_tick.c` as
    /// `CONFIG_KALICO_MOTION_SAMPLE_RATE_HZ` (defaults: 40000 on H7,
    /// 20000 on F4, 10000 on Linux sim). Consumed here to publish
    /// `Engine::sample_period_sec` / `sample_period_cycles` at init time
    /// so `tick_sample`'s guard never fires in production.
    static runtime_sample_rate_hz: u32;
}

impl RuntimeContext {
    /// Initializes the runtime context in place at `rt_ptr`.
    ///
    /// SAFETY: the caller must guarantee single-threaded init before any FFI
    /// call hits the runtime (the FFI shim enforces this via a one-shot
    /// `AtomicBool` guard on `kalico_runtime_init`). This function writes
    /// through raw-pointer projections; it never materializes `&mut
    /// RuntimeContext` and is sound to call against `MaybeUninit::as_mut_ptr()`.
    pub unsafe fn init(rt_ptr: *mut RuntimeContext) {
        // SAFETY: caller guarantees `rt_ptr` is valid for writes and
        // exclusively-owned for the duration of init. We only form raw
        // pointers to fields and never a `&mut RuntimeContext`.
        unsafe {
            // Initialize SharedState.
            let shared_ptr = core::ptr::addr_of_mut!((*rt_ptr).shared);
            shared_ptr.write(SharedState::new());

            // Zero-initialize piece_storage (all entries start zeroed).
            // `UnsafeCell<[PieceEntry; N]>` is layout-compatible with `[PieceEntry; N]`
            // (`UnsafeCell` is `#[repr(transparent)]`).  Writing zeroes is safe
            // because `PieceEntry` is `#[repr(C)]` with no padding and all-zero is a
            // valid bit pattern (start_time=0, coeffs=0.0, duration=0.0).
            let ps_ptr = core::ptr::addr_of_mut!((*rt_ptr).piece_storage);
            core::ptr::write_bytes(
                ps_ptr.cast::<u8>(),
                0u8,
                core::mem::size_of::<UnsafeCell<[crate::piece_ring::PieceEntry; TOTAL_RING_PIECES]>>(
                ),
            );

            // Read C-side clock frequency and sample rate once so the ISR's
            // WidenState + Engine::init_in_place_production both see the same
            // values. Both constants are set at static-init time in
            // `src/runtime_tick.c` before the runtime ever runs.
            let freq = core::ptr::read_volatile(core::ptr::addr_of!(runtime_clock_freq));
            let sample_rate_hz =
                core::ptr::read_volatile(core::ptr::addr_of!(runtime_sample_rate_hz));

            // Publish scheduler tunables to SharedState so the per-axis
            // Klipper timer's empty-queue rescheduling math uses the real
            // sample-period cadence (typically 25 µs at 40 kHz on H7) instead
            // of the `0 → waketime = now` fallback.
            // Integer division is intentional: round-to-nearest cycles.
            #[allow(clippy::integer_division)]
            let sample_period_cycles_init: u32 = if sample_rate_hz == 0 {
                0
            } else {
                (freq + sample_rate_hz / 2) / sample_rate_hz
            };
            #[allow(clippy::integer_division)]
            let dispatcher_floor_cycles_init: u32 = freq / 1_000_000;
            let shared_ref: *const SharedState = core::ptr::addr_of!((*rt_ptr).shared);
            (*shared_ref).sample_period_cycles.store(
                sample_period_cycles_init,
                core::sync::atomic::Ordering::Release,
            );
            (*shared_ref).dispatcher_floor_cycles.store(
                dispatcher_floor_cycles_init,
                core::sync::atomic::Ordering::Release,
            );

            // Initialize FgState.
            let fg_ptr = core::ptr::addr_of_mut!((*rt_ptr).fg);
            fg_ptr.write(UnsafeCell::new(FgState {
                current_stream_id: None,
                armed_t_start_t0: None,
                flush_start_tick: None,
            }));

            // Initialize IsrState — IN-PLACE, field-by-field, to avoid
            // materializing the multi-KB `EngineImpl` on the 8 KB MCU stack.
            let isr_ptr = core::ptr::addr_of_mut!((*rt_ptr).isr);
            let inner_ptr: *mut IsrState = UnsafeCell::raw_get(isr_ptr);
            EngineImpl::init_in_place_production(
                core::ptr::addr_of_mut!((*inner_ptr).engine),
                freq,
                sample_rate_hz,
            );
            core::ptr::addr_of_mut!((*inner_ptr).widen_state).write(WidenState::default());
            core::ptr::addr_of_mut!((*inner_ptr).last_tick_now).write(None);
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SetStepModeError {
    /// Requested `StepMode::Modulated` on an MCU whose capability bitmap
    /// does not advertise `PHASE_STEPPING`. Spec §4.
    CapabilityMissing,
    /// `stepper_idx >= MAX_STEPPER_OIDS`.
    OutOfRange,
}

/// Atomically flip a stepper's `StepMode`. Enforces the capability
/// ceiling: `Modulated` is rejected if the MCU doesn't advertise the
/// phase-stepping bit. Spec §10.
///
/// `Release` ordering on the store pairs with `Acquire` loads in the
/// engine ISR and any foreground reader of `step_modes`.
pub fn set_step_mode(
    shared: &SharedState,
    stepper_idx: u8,
    mode: StepMode,
    mcu_supports_phase: bool,
) -> Result<(), SetStepModeError> {
    if (stepper_idx as usize) >= MAX_STEPPER_OIDS {
        return Err(SetStepModeError::OutOfRange);
    }
    if mode == StepMode::Modulated && !mcu_supports_phase {
        return Err(SetStepModeError::CapabilityMissing);
    }
    // SAFETY: bounds checked above: stepper_idx < MAX_STEPPER_OIDS == step_modes.len()
    #[allow(clippy::indexing_slicing)]
    shared.step_modes[stepper_idx as usize]
        .store(mode as u8, core::sync::atomic::Ordering::Release);
    Ok(())
}

#[cfg(test)]
mod size_task18;

#[cfg(test)]
mod tests;
