FROM ubuntu:24.04 AS base
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y sudo git curl

FROM base

COPY . /klipper
WORKDIR /klipper
RUN ./scripts/ci-install.sh
RUN ./scripts/ci-build.sh
