//! Build script for the runtime crate.
//!
//! Two responsibilities:
//!
//! 1. Register `cfg(loom)` so the `unexpected_cfgs` lint doesn't fire on
//!    `#![cfg(loom)]` markers in loom-only test files. Step-6 plan Phase 1
//!    Task 1.4 runs `RUSTFLAGS="--cfg loom"` against `tests/loom_*.rs`; the
//!    regular host clippy/check build doesn't set the cfg, so without this
//!    hint rustc warns on the attribute. Workspace `[lints]` inheritance
//!    prevents per-crate `[lints.rust]` overrides, so the registration goes
//!    here.
//!
//! 2. Emit sizing constants that vary per target MCU build. Reads four env
//!    vars exported by Klipper's Makefile (which sources them from the
//!    matching `CONFIG_RUNTIME_*` Kconfig values). Defaults match the H7
//!    `large` profile so host-only / sim builds (which don't go through the
//!    Klipper Makefile) still compile.
//!
//!    Spec: docs/superpowers/specs/2026-05-06-runtime-sizing-per-mcu-design.md §4.3.

use std::env;
use std::fs;
use std::path::PathBuf;

fn lookup(name: &str, default: &str) -> String {
    println!("cargo:rerun-if-env-changed={name}");
    env::var(name).unwrap_or_else(|_| default.to_string())
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(loom)");

    let mcp = lookup("KALICO_RUNTIME_MAX_CONTROL_POINTS", "1830");
    let mkv = lookup("KALICO_RUNTIME_MAX_KNOT_VECTOR_LEN", "1850");
    let mdg = lookup("KALICO_RUNTIME_MAX_DEGREE", "10");
    let cpn = lookup("KALICO_RUNTIME_CURVE_POOL_N", "16");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let body = format!(
        "// Auto-generated by runtime/build.rs — do not edit.\n\
         pub const MAX_CONTROL_POINTS: usize = {mcp};\n\
         pub const MAX_KNOT_VECTOR_LEN: usize = {mkv};\n\
         pub const MAX_DEGREE: u8 = {mdg};\n\
         pub const CURVE_POOL_N: usize = {cpn};\n"
    );
    fs::write(out_dir.join("sizing.rs"), body).expect("write sizing.rs");
}
