//! Slicer-dialect comment-pattern matchers. Covers `OrcaSlicer` / `PrusaSlicer`
//! / `BambuStudio`. The matcher itself lands in Task 8; this module just defines
//! the type today.

#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum MarkerKind {
    /// Layer boundary marker. `layer` is `Some(N)` when the slicer emits a
    /// numbered marker (`;LAYER:N`, Cura dialect) and `None` for unnumbered
    /// boundary markers (`;LAYER_CHANGE`, `OrcaSlicer` / `PrusaSlicer` / Bambu dialect).
    LayerChange { layer: Option<u32> },
    /// `;TYPE:WALL-OUTER`, `;TYPE:INFILL`, etc.
    LayerType { name: Box<str> },
    /// `;END_OF_PRINT` and equivalents.
    EndOfPrint,
}

/// Match a comment line (with leading `;` already verified) against known
/// slicer-dialect patterns. Returns `Some(MarkerKind)` if recognized, `None`
/// otherwise. Caller passes the raw comment line (including the leading `;`).
#[must_use]
pub fn match_comment(comment_line: &str) -> Option<MarkerKind> {
    // Strip leading ';' and surrounding whitespace within the comment.
    let body = comment_line.strip_prefix(';')?.trim();

    // ;LAYER:N (Cura)
    if let Some(rest) = body.strip_prefix("LAYER:") {
        if let Ok(n) = rest.trim().parse::<u32>() {
            return Some(MarkerKind::LayerChange { layer: Some(n) });
        }
    }

    // ;LAYER_CHANGE (OrcaSlicer / PrusaSlicer / Bambu — boundary marker
    // without a layer number; layer height comes in a following ;Z: comment).
    if body == "LAYER_CHANGE" {
        return Some(MarkerKind::LayerChange { layer: None });
    }

    // ;TYPE:NAME (Orca, Prusa, Bambu)
    if let Some(rest) = body.strip_prefix("TYPE:") {
        return Some(MarkerKind::LayerType {
            name: rest.trim().to_string().into_boxed_str(),
        });
    }

    // ;END_OF_PRINT and similar
    let upper = body.to_ascii_uppercase();
    if upper == "END_OF_PRINT" || upper == "END OF PRINT" || upper.starts_with("END_GCODE") {
        return Some(MarkerKind::EndOfPrint);
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_orca_layer_change() {
        assert_eq!(
            match_comment(";LAYER:5"),
            Some(MarkerKind::LayerChange { layer: Some(5) })
        );
        assert_eq!(
            match_comment(";LAYER:0"),
            Some(MarkerKind::LayerChange { layer: Some(0) })
        );
        // OrcaSlicer / PrusaSlicer emit `;LAYER_CHANGE` without a number.
        assert_eq!(
            match_comment(";LAYER_CHANGE"),
            Some(MarkerKind::LayerChange { layer: None })
        );
    }

    #[test]
    fn matches_prusa_layer() {
        // PrusaSlicer also emits ;LAYER_CHANGE (handled in matches_orca_layer_change).
        // Cura-style numbered marker:
        assert_eq!(
            match_comment(";LAYER:12"),
            Some(MarkerKind::LayerChange { layer: Some(12) })
        );
    }

    #[test]
    fn matches_type() {
        assert_eq!(
            match_comment(";TYPE:WALL-OUTER"),
            Some(MarkerKind::LayerType {
                name: "WALL-OUTER".to_string().into_boxed_str()
            })
        );
    }

    #[test]
    fn unknown_comment_returns_none() {
        assert_eq!(match_comment("; just a comment"), None);
        assert_eq!(match_comment(";generated by Slic3r"), None);
    }
}
