/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_LOAD_CURVE 0x0010
#define KALICO_MSG_LOAD_CURVE_RESPONSE 0x0011
#define KALICO_MSG_PUSH_SEGMENT 0x0020
#define KALICO_MSG_PUSH_SEGMENT_RESPONSE 0x0021
#define KALICO_MSG_STATUS_EVENT 0x0080
#define KALICO_MSG_CREDIT_FREED 0x0081
#define KALICO_MSG_FAULT_EVENT 0x0082

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0xd2, 0x04, 0xd9, 0x13, 0x3a, 0x8d, 0xd4, 0xf8, 
    0x06, 0x5d, 0xea, 0x62, 0x17, 0x84, 0x3f, 0xa1, 
    0x6b, 0x1a, 0x5d, 0x57, 0xb1, 0x8d, 0x36, 0x4c, 
    0xe3, 0x21, 0xc5, 0x86, 0xda, 0xc4, 0x6c, 0x92
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
