/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_LOAD_CURVE_CUBIC 0x0010
#define KALICO_MSG_LOAD_CURVE_RESPONSE 0x0011
#define KALICO_MSG_PUSH_SEGMENT 0x0020
#define KALICO_MSG_PUSH_SEGMENT_RESPONSE 0x0021
#define KALICO_MSG_CONFIGURE_AXES 0x0030
#define KALICO_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define KALICO_MSG_QUERY_RUNTIME_CAPS 0x0040
#define KALICO_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define KALICO_MSG_RESET_CURVE_POOL 0x0050
#define KALICO_MSG_RESET_CURVE_POOL_RESPONSE 0x0051
#define KALICO_MSG_PUSH_PIECES 0x0060
#define KALICO_MSG_PUSH_PIECES_RESPONSE 0x0061
#define KALICO_MSG_STATUS_EVENT 0x0080
#define KALICO_MSG_CREDIT_FREED 0x0081
#define KALICO_MSG_FAULT_EVENT 0x0082
#define KALICO_MSG_STATUS_HEARTBEAT 0x0083

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0x13, 0x12, 0x1e, 0xad, 0xde, 0xe6, 0x8f, 0xe5, 
    0x92, 0xa0, 0x6a, 0xef, 0xa7, 0xa5, 0xeb, 0x52, 
    0xff, 0xaf, 0x42, 0x40, 0x1b, 0xee, 0xe7, 0x5b, 
    0x21, 0x5b, 0xe8, 0x51, 0xfb, 0xe6, 0x9a, 0xd6
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
