/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_LOAD_CURVE_CUBIC 0x0010
#define KALICO_MSG_LOAD_CURVE_RESPONSE 0x0011
#define KALICO_MSG_PUSH_SEGMENT 0x0020
#define KALICO_MSG_PUSH_SEGMENT_RESPONSE 0x0021
#define KALICO_MSG_CONFIGURE_AXES 0x0030
#define KALICO_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define KALICO_MSG_QUERY_RUNTIME_CAPS 0x0040
#define KALICO_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define KALICO_MSG_STATUS_EVENT 0x0080
#define KALICO_MSG_CREDIT_FREED 0x0081
#define KALICO_MSG_FAULT_EVENT 0x0082

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0x59, 0x03, 0x23, 0xf8, 0x3d, 0x28, 0xe5, 0x16, 
    0x60, 0x22, 0xf2, 0x96, 0xc3, 0x94, 0x53, 0x79, 
    0x5c, 0x6a, 0x89, 0xf0, 0xf9, 0x2e, 0x0d, 0x9a, 
    0x2f, 0xa2, 0xdd, 0x93, 0xec, 0xeb, 0x47, 0x41
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
