// src/stm32/kalico_h7_timer.c
//
// H723-specific TIM5 init + IRQ handler. Spec §2.4 / §4.1 / §4.2 / §4.4.

#include "autoconf.h"
#include "generic/armcm_boot.h" // DECL_ARMCM_IRQ
#include "internal.h"          // STM32-internal helpers — TIM5, RCC, DWT
#include "kalico_runtime.h"
#include "kalico_h7_timer.h"   // shared bench buffer + helper sigs

#if CONFIG_KALICO_RUNTIME && CONFIG_MACH_STM32H7

extern const uint32_t kalico_clock_freq;

extern void* kalico_rt_handle;   // exposed in src/runtime_tick.c

void
kalico_h7_disable_tim5(void)
{
    TIM5->CR1 &= ~TIM_CR1_CEN;
    NVIC_DisableIRQ(TIM5_IRQn);
}

// Helper for Rust's CYCCNT widen-reinit on producer-driven re-enable path.
uint32_t
kalico_h7_read_cyccnt(void)
{
    return DWT->CYCCNT;
}

void
kalico_h7_enable_tim5(void)
{
    TIM5->SR = ~TIM_SR_UIF;       // clear stale UIF before enabling
    TIM5->CR1 |= TIM_CR1_CEN;
    NVIC_EnableIRQ(TIM5_IRQn);
}

void
kalico_h7_timer_init(void)
{
    // Init invariant (spec §2.4): MUST disable + clear before any path could fire.
    TIM5->CR1 &= ~TIM_CR1_CEN;
    TIM5->SR = 0;
    NVIC_DisableIRQ(TIM5_IRQn);

    // Enable TIM5 clock.
    RCC->APB1LENR |= RCC_APB1LENR_TIM5EN;

    // 40 kHz tick: PSC = 0, ARR = (clock_freq / 40000) - 1.
    TIM5->PSC = 0;
    TIM5->ARR = (kalico_clock_freq / 40000U) - 1U;

    // Auto-reload, update interrupt enable.
    TIM5->CR1 = TIM_CR1_ARPE;
    TIM5->DIER = TIM_DIER_UIE;

    // Enable DWT cycle counter for raw_cyccnt reads in the ISR.
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    // Set IRQ priority 3 (Cortex-M: lower number = higher urgency).
    // Below SysTick (2) and USB (1) per spec §2.4.
    NVIC_SetPriority(TIM5_IRQn, 3);

    // Don't enable yet — runtime_init pushes segments first; first push triggers
    // kalico_h7_enable_tim5() via the producer protocol.
}

// Cycle-count bench buffer storage. Declared `extern` in kalico_h7_timer.h
// so src/runtime_tick.c's bench command can read it. SAFETY: only this ISR
// writes; foreground reads after observing `count == target`.
volatile uint32_t kalico_bench_samples_buf[KALICO_BENCH_MAX_SAMPLES];
volatile uint16_t kalico_bench_count = 0;
volatile uint16_t kalico_bench_target = 0;
volatile uint8_t  kalico_bench_isolate = 0;

void
TIM5_IRQHandler(void)
{
    TIM5->SR = ~TIM_SR_UIF;            // entry-time ack (spec §2.4)
    uint32_t before = DWT->CYCCNT;
    if (kalico_rt_handle) {
        kalico_runtime_tick(kalico_rt_handle, before);
    }
    uint32_t after = DWT->CYCCNT;

    // Bench capture (Task 27). Wraps subtract correctly modulo 2^32.
    if (kalico_bench_count < kalico_bench_target) {
        kalico_bench_samples_buf[kalico_bench_count] = after - before;
        kalico_bench_count++;
    }
    // No late ack.
}

// Klipper's IRQ vector-table dispatch is generated by scripts/buildcommands.py
// from DECL_ARMCM_IRQ entries. Without this, TIM5_IRQHandler will not be wired
// into the vector table and the IRQ silently drops.
DECL_ARMCM_IRQ(TIM5_IRQHandler, TIM5_IRQn);

#endif // CONFIG_KALICO_RUNTIME && CONFIG_MACH_STM32H7
