/*
* kalico_runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-28-layer-4-mcu-framework-stub-design.md.
*/


#ifndef KALICO_RUNTIME_H
#define KALICO_RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define KALICO_TRIP_EVENT_V1_HEADER_LEN 15

#define KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN 5

#define KALICO_TRIP_EVENT_V1_FMT_VERSION 1

#define KALICO_TRIP_EVENT_V1_MAX_LEN (KALICO_TRIP_EVENT_V1_HEADER_LEN + (MAX_STEPPERS * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN))

enum SourceKind {
  Physical = 0,
  TmcDiag = 1,
};
typedef uint8_t SourceKind;

enum ArmPolicy {
  TripImmediately = 0,
  WaitForClear = 1,
  IgnoreUntilMoving = 2,
};
typedef uint8_t ArmPolicy;

typedef struct SourceConfig SourceConfig;

typedef struct VelocityAxis VelocityAxis;

/**
 * The opaque type C sees — never dereferenced on the C side.
 * Matches spec §3.2 / §5.6 handle discipline.
 */
typedef struct KalicoRuntime {
  uint8_t _private[0];
} KalicoRuntime;

/**
 * Handle to a loaded curve. 32-bit packed `(slot_idx, generation)` per
 * spec §10.1. ABA-defeating: at `Q_N_MAX = 256` the u16 gen wraps over
 * `65536 - 256 = 65280` allocations, which exceeds any realistic in-flight
 * stale-handle window.
 */
typedef struct CurveHandle {
  uint16_t slot_idx;
  uint16_t generation;
} CurveHandle;
/**
 * Sentinel for hold segments (§6.5). The ISR short-circuits on the
 * `SEGMENT_FLAG_HOLD_SEGMENT` flag bit BEFORE looking up this handle, so
 * the sentinel is never resolved through `CurvePool::lookup`.
 */
#define CurveHandle_HOLD_SEGMENT_SENTINEL (CurveHandle){ .slot_idx = UINT16_MAX, .generation = UINT16_MAX }
/**
 * Sentinel for unused curve handle slots in multi-handle segment structs.
 * Distinct from `HOLD_SEGMENT_SENTINEL` to avoid confusion.
 */
#define CurveHandle_UNUSED_SENTINEL (CurveHandle){ .slot_idx = (UINT16_MAX - 1), .generation = (UINT16_MAX - 1) }

/**
 * Trace sample (§13.2). `repr(C)` aligned (NOT packed) to avoid unaligned
 * `u64` access on Cortex-M7. Carries `curve_handle` so foreground reclaim
 * (`drain_and_reclaim` → `pool.confirm_retired(handle)`) can route
 * `SEGMENT_END` events back to the right pool slot per §10.4.
 */
typedef struct TraceSample {
  uint64_t tick;
  float motor_a;
  float motor_b;
  float motor_z;
  float motor_e;
  uint32_t segment_id;
  struct CurveHandle curve_handle;
  uint8_t flags;
  uint8_t _pad[7];
} TraceSample;













extern void runtime_tick_enable(void);

extern void runtime_tick_disable(void);

extern uint32_t runtime_cyccnt_read(void);

/**
 * Init-once. Spec §3.2.
 *
 * Returns a valid handle on the first successful call; null on any
 * subsequent call. The handle is the address of the static
 * `RuntimeContext` storage; its lifetime is `'static`.
 */
struct KalicoRuntime *runtime_handle_create(void);

/**
 * Push a segment. Producer protocol per spec §4.4 + §10.1.
 *
 * Step 7-B: four per-axis curve handles (x, y, z, e) replace the single
 * `curve_handle_packed`. Each is a wire-encoded `(generation << 16) |
 * slot_idx`. `e_mode` selects the extruder evaluation strategy (0 =
 * CoupledToXy, 1 = Independent, 2 = Travel). `extrusion_ratio_bits` is
 * `f32::to_bits()` of the extrusion_per_xy_mm scalar for CoupledToXy mode.
 *
 * `out_accepted_segment_id` and `out_credit_epoch` may be NULL (host
 * callers that don't need them); when present they receive the values
 * published into `SharedState` on success — host caller sees the same
 * values via the `kalico_push_response` schema (§5.3).
 */
int32_t runtime_handle_push_segment(struct KalicoRuntime *rt,
                                    uint32_t id,
                                    uint32_t x_handle_packed,
                                    uint32_t y_handle_packed,
                                    uint32_t z_handle_packed,
                                    uint32_t e_handle_packed,
                                    uint64_t t_start,
                                    uint64_t t_end,
                                    uint8_t kinematics,
                                    uint8_t e_mode,
                                    uint32_t extrusion_ratio_bits,
                                    uint32_t *out_accepted_segment_id,
                                    uint32_t *out_credit_epoch);

/**
 * Load a scalar curve into a slab slot. Producer-side validation rejects
 * bad data. Returns the freshly issued `(slot, gen)` packed handle via
 * `out_handle_packed` on success.
 *
 * Step 7-B: accepts scalar control points (1D). No weights (polynomial-only).
 */
int32_t runtime_handle_load_curve(struct KalicoRuntime *rt,
                                  uint16_t slot_idx,
                                  const float *control_points_flat,
                                  uint16_t n_cp,
                                  const float *knots,
                                  uint16_t n_knots,
                                  uint8_t degree,
                                  uint32_t *out_handle_packed);

/**
 * Validate a versioned blob payload's leading version byte (§4.2).
 * Foreground entrypoint for the C handler that reads payload bytes off
 * the wire and routes the post-version-byte slice into the Step-5
 * flat-pointer load path. Returns `KALICO_OK` on a recognised version
 * or `KALICO_ERR_PROTOCOL_VERSION_UNSUPPORTED` otherwise.
 */
int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

/**
 * Diagnostic: per-slot generation snapshot (spec §10.4 + Round-1 B9).
 * Used after a fault for host-side recovery decisions. Writes the
 * per-slot `current_gen` and `last_retired_gen` into the out-params.
 */
int32_t runtime_handle_query_pool_state(struct KalicoRuntime *rt,
                                        uint16_t slot_idx,
                                        uint16_t *out_current_gen,
                                        uint16_t *out_last_retired_gen);

/**
 * ISR entrypoint. Spec §3.2 / §4.2.
 * `raw_cyccnt` is the raw 32-bit DWT->CYCCNT value; Rust widens to u64.
 * Skips null-check (caller is the C ISR shim with stable handle).
 */
void runtime_handle_tick(struct KalicoRuntime *rt, uint32_t raw_cyccnt);

/**
 * Foreground drain. Returns count of samples written.
 *
 * Phase 11 §10.4 expansion: alongside writing the sample to the wire
 * buffer, this also calls `pool.confirm_retired` for any sample
 * carrying `TRACE_FLAG_SEGMENT_END`, so curve-pool slots get reclaimed
 * in lockstep with the trace ship-out (one drain pass = one
 * foreground-side wire emit + one reclaim cursor advance).
 *
 * `out_saw_segment_end` (optional, may be NULL): set to `1` on return
 * when the drain consumed at least one `TRACE_FLAG_SEGMENT_END`
 * sample, else `0`. Closure-review fix: `kalico_credit_freed` emission
 * in `runtime_drain` previously gated only on the second
 * (drain-and-reclaim) leg's bit, but the first leg routinely consumes
 * every `SEGMENT_END` under steady-state push, suppressing the credit
 * event and deadlocking host flow control. The C handler now ORs this
 * bit with the reclaim leg's bit.
 */
uint32_t runtime_handle_drain_trace(struct KalicoRuntime *rt,
                                    struct TraceSample *out_buf,
                                    uint32_t out_cap,
                                    uint8_t *out_saw_segment_end);

uint8_t runtime_handle_status(struct KalicoRuntime *rt);

int32_t runtime_handle_last_error(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_counter(struct KalicoRuntime *rt);

/**
 * Read the widened MCU clock (§11.4 seqlock). Returns the most recently
 * published u64 cycle count from the ISR. Safe to call from foreground
 * at any time — the seqlock retries if it sees a torn read.
 */
uint64_t runtime_handle_widened_now(struct KalicoRuntime *rt);

/**
 * Read the credit-flow epoch counter (§5.3 + §10.4). Bumped on each
 * `kalico_stream_flush` so the host can detect mid-stream resets.
 */
uint32_t runtime_handle_credit_epoch(struct KalicoRuntime *rt);

/**
 * Read the cumulative-accepted segment id cursor (§5.3 + §4.1.5).
 * Mirrors the value placed into the `kalico_push_response` schema.
 */
uint32_t runtime_handle_accepted_segment_id(struct KalicoRuntime *rt);

/**
 * Read the retired-through segment id cursor (§5.3 + §4.1.5). Advances
 * monotonically as the engine retires segments — host uses this to
 * gate flow control and to know when a stream-terminal hand-off is
 * safe to call.
 */
uint32_t runtime_handle_retired_through_segment_id(struct KalicoRuntime *rt);

/**
 * Read the currently-active segment id (`0` if engine is Idle/Drained
 * or pre-stream).
 */
uint32_t runtime_handle_current_segment_id(struct KalicoRuntime *rt);

/**
 * Approximate queue depth — number of segments the foreground has
 * pushed minus the number the ISR has retired through. Useful as a
 * status-frame breadcrumb but NOT a synchronization primitive (both
 * cursors lag the actual SPSC state by an unbounded number of ticks
 * in the worst case). Returns saturating-subtraction in u8 range
 * (`Q_N - 1` is the structural cap; saturate at 255 just in case).
 */
uint8_t runtime_handle_queue_depth(struct KalicoRuntime *rt);

/**
 * Read the latched `fault_detail` payload (§9.2). Mirrors the value
 * the foreground emits with the async `kalico_fault` event. `0` when
 * no fault has latched OR the latched fault carries no detail.
 */
uint32_t runtime_handle_fault_detail(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the configured `steps_per_mm` for axis `oid` (0..=3
 * in motor space). Returns 0.0 if `oid` is out of range or runtime
 * uninitialised. Used by Phase 4 sim test to verify that
 * `configure_axes_blob` reached the engine.
 */
float runtime_handle_get_axis_steps_per_mm(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Seed the engine's widen state with a u64 baseline so the engine's
 * `now` agrees with Klipper's widened MCU clock. Called by the Linux
 * sim host once at runtime_init, BEFORE the engine pthread starts
 * ticking. `baseline_widened_clock` is whatever value timer_read_time()
 * would map to in the widened (no-wrap) frame at this instant; the
 * caller computes it from clock_gettime so wrap counts already passed
 * in u32 timer_read_time space are folded in.
 */
void runtime_handle_seed_widen(struct KalicoRuntime *rt, uint64_t baseline_widened_clock);

/**
 * Diagnostic: read most recent post-PA/IS motor position for axis `oid`.
 */
float kalico_runtime_get_axis_motor(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Diagnostic: read most recent (now, t_start, duration) into the three
 * out pointers. All u64 cycle counts.
 */
void kalico_runtime_get_last_timing(struct KalicoRuntime *rt,
                                    uint64_t *now_out,
                                    uint64_t *t_start_out,
                                    uint64_t *duration_out);

/**
 * Diagnostic: read step accumulator (sub-step residual + integer state)
 * for axis `oid`.  Returns 0.0 if invalid.
 */
double kalico_runtime_get_axis_accumulator(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Read the cumulative signed step count for stepper `oid` (0-indexed).
 * Returns 0 for an invalid `rt` / uninitialised runtime / out-of-range oid.
 * Used by the sim diagnostic command `runtime_sim_stepper_count_query`.
 */
int32_t kalico_runtime_get_stepper_count(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Configure axis mapping and kinematics for this MCU. Minimal stub for
 * Step 7-B MVP — accepts `kinematics_tag` (0 = CoreXyAndE, 1 =
 * CartesianXyzAndE) and validates. Full motor-config blob
 * deserialization is deferred to Step 7-C.
 */
int32_t kalico_configure_axes(struct KalicoRuntime *rt, uint8_t kinematics_tag);

/**
 * Extended blob layout (25 bytes):
 *
 * ```text
 * byte  0     kinematics_tag  (0 = CoreXY+E, 1 = Cartesian+E)
 * byte  1     present_mask    (bit i set → motor i is present)
 * byte  2     awd_mask        (bit i set → motor i is AWD)
 * byte  3     invert_mask     (bit i set → motor i direction inverted)
 * bytes 4-7   steps_per_mm[0] (f32 LE)
 * bytes 8-11  steps_per_mm[1] (f32 LE)
 * bytes 12-15 steps_per_mm[2] (f32 LE)
 * bytes 16-19 steps_per_mm[3] (f32 LE)
 *             -- present only in extended (25-byte) format --
 * byte 20     mcu_caps        (bit 0 = mcu_supports_phase_stepping)
 * byte 21     step_mode[0]    (0 = Modulated, 1 = StepTime)
 * byte 22     step_mode[1]
 * byte 23     step_mode[2]
 * byte 24     step_mode[3]
 * ```
 *
 * Legacy hosts emit the 20-byte format; the MCU defaults all steppers to
 * `StepTime` in that case. Any other `blob_len` is rejected.
 */
int32_t kalico_runtime_configure_axes_blob(struct KalicoRuntime *rt,
                                           const uint8_t *blob_ptr,
                                           uint32_t blob_len);

/**
 * Phase 11 Task 11.2 foreground reclaim drain pipeline. Drains up to
 * `limit` trace samples from the ring, calls `pool.confirm_retired`
 * for each `SEGMENT_END` observed, and returns a 32-bit packed
 * status:
 *
 * - Bits 0..=15 — count of samples drained this call.
 * - Bit 16     — set if a fresh trace-overflow fault latched (§13.1).
 * - Bit 17     — set if at least one `SEGMENT_END` was observed
 *   (caller emits one or more `kalico_credit_freed`
 *   events keyed off the updated cursors).
 *
 * The C handler (`runtime_drain` `DECL_TASK` in `src/runtime_tick.c`)
 * uses this single-call form so the trace-drain + reclaim + fault-
 * latch pipeline is one round-trip per drain wake-up.
 */
uint32_t kalico_runtime_drain_and_reclaim(struct KalicoRuntime *rt, uint32_t limit);

/**
 * `kalico_stream_open` — assert host-MCU stream identity (§8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_open(struct KalicoRuntime *rt,
                                   uint32_t stream_id,
                                   uint32_t *out_credit_epoch);

/**
 * `kalico_stream_arm` — commit the priming buffer (§6.4 / §8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_arm(struct KalicoRuntime *rt,
                                  uint64_t t_start_t0,
                                  uint32_t arm_lead_cycles,
                                  uint64_t *out_armed_t_start);

/**
 * `kalico_stream_terminal` — mark the last segment id of the stream
 * (§8.3). Phase-6 stub.
 */
int32_t kalico_runtime_stream_terminal(struct KalicoRuntime *rt, uint32_t segment_id);

/**
 * `kalico_stream_flush` — `force_idle` handshake (§8.5).
 *
 * `flush()` projects to both halves under disabled-IRQ, so we hand it
 * the raw `*mut RuntimeContext` directly rather than going through
 * the foreground-only `project_fg` helper. SAFETY: caller is the
 * single-threaded foreground command dispatch.
 */
int32_t kalico_runtime_stream_flush(struct KalicoRuntime *rt, uint32_t *out_credit_epoch);

/**
 * `kalico_clock_sync_request` — RTT-aware clock-sync ping (§12.1).
 * Phase-6 stub. Out-param receives the MCU local-clock value sampled
 * inside the FFI on success.
 */
int32_t kalico_runtime_clock_sync_request(struct KalicoRuntime *rt,
                                          uint32_t request_id,
                                          uint32_t host_send_time_lo,
                                          uint32_t host_send_time_hi,
                                          uint64_t *out_mcu_clock);

/**
 * Arm an endstop. The blob layouts match spec §3.1:
 * - `sources`: `source_count` records of 11 bytes each
 *   (kind u8, gpio u16 LE, polarity u8, arm_policy u8, sample_n u8,
 *    velocity_axis u8, v_min_q16 u32 LE).
 * - `steppers`: `stepper_count` records of 1 byte (stepper_oid u8).
 *
 * Writes one of the spec §3.2 status values into `*out_status`:
 * 0 = Armed, 1 = AlreadyTripped, 2 = Rejected.
 */
int32_t kalico_endstop_arm(uint32_t arm_id,
                           uint32_t arm_clock_lo,
                           uint32_t arm_clock_hi,
                           uint8_t source_count,
                           const uint8_t *sources_ptr,
                           uintptr_t sources_len,
                           uint8_t stepper_count,
                           const uint8_t *steppers_ptr,
                           uintptr_t steppers_len,
                           uint8_t *out_status);

/**
 * Disarm an active endstop arm. `out_status` writes spec §3.5 codes:
 * 0 = Disarmed, 1 = AlreadyTripped, 2 = Unknown.
 */
int32_t kalico_endstop_disarm(uint32_t arm_id, uint8_t *out_status);

/**
 * Drain the next pending trip event into a host-side buffer.
 *
 * Wire format v1, little-endian, total length =
 * `KALICO_TRIP_EVENT_V1_HEADER_LEN + stepper_count *
 * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN`. Header layout:
 * `arm_id u32 | trip_clock_lo u32 | trip_clock_hi u32 |
 *  trip_source_idx u8 | fmt_version u8 (=1) | stepper_count u8`.
 * Each stepper record: `stepper_oid u8 | step_count i32`.
 *
 * Returns:
 * - `1`  + `*out_actual_len` = encoded length: an event was drained.
 * - `0`  + `*out_actual_len = 0`: no event ready.
 * - `KALICO_ERR_NULL_PTR` on argument errors (incl. out_buf too small).
 */
int32_t kalico_endstop_poll_trip(uint8_t *out_buf,
                                 uintptr_t out_buf_len,
                                 uintptr_t *out_actual_len);

/**
 * Push a sampled GPIO level into the runtime's abstract pin table.
 *
 * The runtime's endstop module reads pin levels from an internal
 * `PIN_LEVELS: [AtomicBool; MAX_GPIO_PINS]` table (rust/runtime/src/
 * endstop.rs:311). The C ISR shim samples real GPIOs via
 * `gpio_in_read` once per modulation tick (TIM5_IRQHandler at
 * src/stm32/runtime_tick_h7.c, just before `runtime_handle_tick`)
 * and pushes each result through this FFI before `endstop::tick`
 * observes it. Sim builds (Renode e2e at
 * tools/test_renode_endstop_e2e.py) call the same FFI directly via
 * the `command_runtime_sim_endstop_set_pin` shim, bypassing real GPIO.
 */
int32_t kalico_endstop_set_pin_level(uint16_t gpio, uint8_t level);

/**
 * Flip a stepper's `StepMode` at runtime. Spec §10.
 *
 * `mode`: 0 = Modulated (phase-stepping), 1 = StepTime (classic).
 * `mcu_supports_phase`: non-zero if the MCU advertises phase-stepping
 * capability.
 *
 * Returns:
 * - `KALICO_OK` on success.
 * - `KALICO_ERR_INVALID_HANDLE` if `handle` is null or
 *   `stepper_idx >= MAX_STEPPER_OIDS`.
 * - `KALICO_ERR_INVALID_ARG` if `mode` is not a recognised `StepMode`
 *   discriminant.
 * - `KALICO_ERR_CAPABILITY_MISSING` if `mode == Modulated` and
 *   `mcu_supports_phase == 0`.
 */
int32_t kalico_runtime_set_step_mode(struct KalicoRuntime *rt,
                                     uint8_t stepper_idx,
                                     uint8_t mode,
                                     uint8_t mcu_supports_phase);

/**
 * Compute the absolute MCU clock cycle at which `stepper_idx` should
 * fire its next step. Used by the configure/segment-load arming path.
 *
 * On success writes the cycle count to `*out_cycles_abs` and the step
 * direction to `*out_dir` (`+1` = forward / positive, `-1` = reverse /
 * negative), then returns `KALICO_OK`.
 * Returns `KALICO_ERR_NO_STEP` when the active segment cannot produce
 * another step (caller must NOT register the timer; the engine re-arms
 * on the next `push_segment`).
 *
 * `out_dir` may be NULL; if so the direction is computed but discarded.
 *
 * Returns:
 * - `KALICO_OK` + `*out_cycles_abs` and `*out_dir` set on success.
 * - `KALICO_ERR_INVALID_HANDLE` for a null `rt` or `out_cycles_abs`.
 * - `KALICO_ERR_NO_STEP` if no step is available.
 */
int32_t kalico_runtime_arm_step_timer(struct KalicoRuntime *rt,
                                      uint8_t stepper_idx,
                                      uint64_t now_cycles,
                                      uint64_t *out_cycles_abs,
                                      int8_t *out_dir);

/**
 * Compute the next step time for `stepper_idx`. Identical semantics to
 * `kalico_runtime_arm_step_timer`; provided as a separate symbol so the
 * C-side per-stepper `struct timer` ISR re-arm path has a descriptively
 * named entry point. Future engine work may diverge the two.
 *
 * `out_dir` may be NULL; if so the direction is computed but discarded.
 *
 * Returns:
 * - `KALICO_OK` + `*out_cycles_abs` and `*out_dir` set on success.
 * - `KALICO_ERR_INVALID_HANDLE` for a null `rt` or `out_cycles_abs`.
 * - `KALICO_ERR_NO_STEP` if no step is available.
 */
int32_t kalico_runtime_compute_next_step_time(struct KalicoRuntime *rt,
                                              uint8_t stepper_idx,
                                              uint64_t now_cycles,
                                              uint64_t *out_cycles_abs,
                                              int8_t *out_dir);

/**
 * Read the current `StepMode` discriminant for `stepper_idx`.
 *
 * Used by the C-side `arm_step_time_steppers_after_push` to determine
 * whether a stepper should be registered with Klipper's scheduler (mode
 * `StepTime = 1`) or driven by the TIM5 ISR (mode `Modulated = 0`).
 *
 * Returns:
 * - `0`    — `StepMode::Modulated` (phase-stepping via TIM5 ISR).
 * - `1`    — `StepMode::StepTime`  (classic Klipper timer scheduling).
 * - `0xFF` — null `rt`, `INIT_DONE == false`, or `stepper_idx` out of range.
 */
uint8_t kalico_runtime_get_step_mode(struct KalicoRuntime *rt, uint8_t stepper_idx);

/**
 * Count how many steppers are currently in `StepMode::Modulated`.
 *
 * Used by `runtime_tick_enable` (C-side, spec §6.3) to decide whether
 * TIM5 is needed: if the count is zero, TIM5 has no work and is left
 * disabled. F4 (no `PHASE_STEPPING` capability) always hits this path;
 * H7 in an all-StepTime config also leaves TIM5 idle.
 *
 * Returns `0` for a null `rt` or uninitialised runtime.
 */
uint8_t kalico_runtime_count_modulated_steppers(struct KalicoRuntime *rt);

#endif  /* KALICO_RUNTIME_H */
