/*
* kalico_nurbs.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-26-nurbs-evaluation-library-design.md.
*/


#ifndef KALICO_NURBS_H
#define KALICO_NURBS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Borrowed arc-length table. Available on host and MCU. Pure lookup.
 */
typedef struct kalico_nurbs_ArcLengthTableRef_f32 kalico_nurbs_ArcLengthTableRef_f32;

/**
 * Borrowed, slice-backed scalar NURBS. Available on host and MCU.
 *
 * Constructed either via `ScalarNurbs::as_view` (host) or
 * `ScalarNurbsRef::try_new` / `try_from_wire` (MCU + zero-copy paths).
 */
typedef struct kalico_nurbs_ScalarNurbsRef_f32 kalico_nurbs_ScalarNurbsRef_f32;

typedef struct kalico_nurbs_VectorNurbsRef_f32__3 kalico_nurbs_VectorNurbsRef_f32__3;

/**
 * Evaluate a scalar NURBS at parameter `u`. Returns the position.
 *
 * Caller must guarantee `curve` is a valid (non-null, properly initialized)
 * pointer to a `ScalarNurbsRef<f32>` with stable lifetime through the call.
 */
float kalico_nurbs_eval_f32(const struct kalico_nurbs_ScalarNurbsRef_f32 *curve, float u);

/**
 * Evaluate a vector NURBS in R^3 at parameter `u`. Writes the resulting
 * 3-vector into `out` (caller-allocated, length 3).
 */
void kalico_nurbs_vector_eval_3_f32(const struct kalico_nurbs_VectorNurbsRef_f32__3 *curve,
                                    float u,
                                    float *out);

/**
 * Look up a parameter `u` corresponding to arc length `s` in a precomputed table.
 */
float kalico_nurbs_param_from_arc_length_f32(const struct kalico_nurbs_ArcLengthTableRef_f32 *table,
                                             float s);

#endif  /* KALICO_NURBS_H */
