/*
* kalico_runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-28-layer-4-mcu-framework-stub-design.md.
*/


#ifndef KALICO_RUNTIME_H
#define KALICO_RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define KALICO_TRIP_EVENT_V1_HEADER_LEN 15

#define KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN 5

#define KALICO_TRIP_EVENT_V1_FMT_VERSION 1

#define KALICO_TRIP_EVENT_V1_MAX_LEN (KALICO_TRIP_EVENT_V1_HEADER_LEN + (MAX_STEPPERS * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN))

enum SourceKind {
  Physical = 0,
  TmcDiag = 1,
};
typedef uint8_t SourceKind;

enum ArmPolicy {
  TripImmediately = 0,
  WaitForClear = 1,
  IgnoreUntilMoving = 2,
};
typedef uint8_t ArmPolicy;

typedef struct SourceConfig SourceConfig;

typedef struct VelocityAxis VelocityAxis;

/**
 * The opaque type C sees — never dereferenced on the C side.
 * Matches spec §3.2 / §5.6 handle discipline.
 */
typedef struct KalicoRuntime {
  uint8_t _private[0];
} KalicoRuntime;

/**
 * Handle to a loaded curve. 32-bit packed `(slot_idx, generation)` per
 * spec §10.1. ABA-defeating: at `Q_N_MAX = 256` the u16 gen wraps over
 * `65536 - 256 = 65280` allocations, which exceeds any realistic in-flight
 * stale-handle window.
 */
typedef struct CurveHandle {
  uint16_t slot_idx;
  uint16_t generation;
} CurveHandle;
/**
 * Sentinel for hold segments (§6.5). The ISR short-circuits on the
 * `SEGMENT_FLAG_HOLD_SEGMENT` flag bit BEFORE looking up this handle, so
 * the sentinel is never resolved through `CurvePool::lookup`.
 */
#define CurveHandle_HOLD_SEGMENT_SENTINEL (CurveHandle){ .slot_idx = UINT16_MAX, .generation = UINT16_MAX }
/**
 * Sentinel for unused curve handle slots in multi-handle segment structs.
 * Distinct from `HOLD_SEGMENT_SENTINEL` to avoid confusion.
 */
#define CurveHandle_UNUSED_SENTINEL (CurveHandle){ .slot_idx = (UINT16_MAX - 1), .generation = (UINT16_MAX - 1) }

/**
 * Trace sample (§13.2). `repr(C)` aligned (NOT packed) to avoid unaligned
 * `u64` access on Cortex-M7. Carries `curve_handle` so foreground reclaim
 * (`drain_and_reclaim` → `pool.confirm_retired(handle)`) can route
 * `SEGMENT_END` events back to the right pool slot per §10.4.
 */
typedef struct TraceSample {
  uint64_t tick;
  float motor_a;
  float motor_b;
  float motor_z;
  float motor_e;
  uint32_t segment_id;
  struct CurveHandle curve_handle;
  uint8_t flags;
  uint8_t _pad[7];
} TraceSample;













extern void runtime_tick_enable(void);

extern void runtime_tick_disable(void);

extern uint32_t runtime_cyccnt_read(void);

/**
 * Init-once. Spec §3.2.
 *
 * Returns a valid handle on the first successful call; null on any
 * subsequent call. The handle is the address of the static
 * `RuntimeContext` storage; its lifetime is `'static`.
 */
struct KalicoRuntime *runtime_handle_create(void);

/**
 * Push a segment. Producer protocol per spec §4.4 + §10.1.
 *
 * Step 7-B: four per-axis curve handles (x, y, z, e) replace the single
 * `curve_handle_packed`. Each is a wire-encoded `(generation << 16) |
 * slot_idx`. `e_mode` selects the extruder evaluation strategy (0 =
 * CoupledToXy, 1 = Independent, 2 = Travel). `extrusion_ratio_bits` is
 * `f32::to_bits()` of the extrusion_per_xy_mm scalar for CoupledToXy mode.
 *
 * `out_accepted_segment_id` and `out_credit_epoch` may be NULL (host
 * callers that don't need them); when present they receive the values
 * published into `SharedState` on success — host caller sees the same
 * values via the `kalico_push_response` schema (§5.3).
 */
int32_t runtime_handle_push_segment(struct KalicoRuntime *rt,
                                    uint32_t id,
                                    uint32_t x_handle_packed,
                                    uint32_t y_handle_packed,
                                    uint32_t z_handle_packed,
                                    uint32_t e_handle_packed,
                                    uint64_t t_start,
                                    uint64_t t_end,
                                    uint8_t kinematics,
                                    uint8_t e_mode,
                                    uint32_t extrusion_ratio_bits,
                                    uint32_t *out_accepted_segment_id,
                                    uint32_t *out_credit_epoch);

/**
 * Load a scalar curve into a slab slot. Producer-side validation rejects
 * bad data. Returns the freshly issued `(slot, gen)` packed handle via
 * `out_handle_packed` on success.
 *
 * Step 7-B: accepts scalar control points (1D). No weights (polynomial-only).
 */
int32_t runtime_handle_load_curve(struct KalicoRuntime *rt,
                                  uint16_t slot_idx,
                                  const float *control_points_flat,
                                  uint16_t n_cp,
                                  const float *knots,
                                  uint16_t n_knots,
                                  uint8_t degree,
                                  uint32_t *out_handle_packed);

/**
 * Validate a versioned blob payload's leading version byte (§4.2).
 * Foreground entrypoint for the C handler that reads payload bytes off
 * the wire and routes the post-version-byte slice into the Step-5
 * flat-pointer load path. Returns `KALICO_OK` on a recognised version
 * or `KALICO_ERR_PROTOCOL_VERSION_UNSUPPORTED` otherwise.
 */
int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

/**
 * Diagnostic: per-slot generation snapshot (spec §10.4 + Round-1 B9).
 * Used after a fault for host-side recovery decisions. Writes the
 * per-slot `current_gen` and `last_retired_gen` into the out-params.
 */
int32_t runtime_handle_query_pool_state(struct KalicoRuntime *rt,
                                        uint16_t slot_idx,
                                        uint16_t *out_current_gen,
                                        uint16_t *out_last_retired_gen);

/**
 * ISR entrypoint. Spec §3.2 / §4.2.
 * `raw_cyccnt` is the raw 32-bit DWT->CYCCNT value; Rust widens to u64.
 * Skips null-check (caller is the C ISR shim with stable handle).
 */
void runtime_handle_tick(struct KalicoRuntime *rt, uint32_t raw_cyccnt);

/**
 * TIM5 ISR callback for the Modulated (polled-tick StepAccumulator)
 * path (spec §3.2, T10).
 *
 * Computes the widened MCU clock inline from
 * `timer_read_time()` + `stats_send_time_high` (same widening rule as
 * `runtime_handle_widened_now`), then dispatches into
 * `Engine::runtime_modulated_tick`.
 *
 * Called from `TIM5_IRQHandler` in `src/stm32/runtime_tick_{h7,f4}.c`,
 * which is itself only enabled when `count_modulated_steppers > 0`
 * (see `runtime_tick_enable`). For the all-StepTime MVP this entry
 * is never invoked because TIM5 stays disabled.
 */
void kalico_runtime_modulated_tick(struct KalicoRuntime *rt);

/**
 * Foreground drain. Returns count of samples written.
 *
 * Phase 11 §10.4 expansion: alongside writing the sample to the wire
 * buffer, this also calls `pool.confirm_retired` for any sample
 * carrying `TRACE_FLAG_SEGMENT_END`, so curve-pool slots get reclaimed
 * in lockstep with the trace ship-out (one drain pass = one
 * foreground-side wire emit + one reclaim cursor advance).
 *
 * `out_saw_segment_end` (optional, may be NULL): set to `1` on return
 * when the drain consumed at least one `TRACE_FLAG_SEGMENT_END`
 * sample, else `0`. Closure-review fix: `kalico_credit_freed` emission
 * in `runtime_drain` previously gated only on the second
 * (drain-and-reclaim) leg's bit, but the first leg routinely consumes
 * every `SEGMENT_END` under steady-state push, suppressing the credit
 * event and deadlocking host flow control. The C handler now ORs this
 * bit with the reclaim leg's bit.
 */
uint32_t runtime_handle_drain_trace(struct KalicoRuntime *rt,
                                    struct TraceSample *out_buf,
                                    uint32_t out_cap,
                                    uint8_t *out_saw_segment_end);

uint8_t runtime_handle_status(struct KalicoRuntime *rt);

int32_t runtime_handle_last_error(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_counter(struct KalicoRuntime *rt);

/**
 * Read the widened MCU clock. Spec §3.9 — on-demand widening from
 * Klipper's `timer_read_time` + the `stats_send_time` / `stats_send_time_high`
 * counters that Klipper's stats task maintains (basecmd.c). Replaces the
 * pre-emission-rewrite SharedState seqlock dependency: TIM5 is off when
 * `count_modulated_steppers == 0`, so the seqlock would not be re-published
 * in StepTime-only configurations. The stats task runs unconditionally,
 * so this widening advances regardless of engine activity.
 *
 * Mirrors the C-side `runtime_widened_host_clock` in `src/runtime_tick.c`.
 * Foreground-only — `timer_read_time()` is not re-entrant with the
 * stats-task wrap update; do not call from ISR context.
 */
uint64_t runtime_handle_widened_now(struct KalicoRuntime *rt);

/**
 * Read the credit-flow epoch counter (§5.3 + §10.4). Bumped on each
 * `kalico_stream_flush` so the host can detect mid-stream resets.
 */
uint32_t runtime_handle_credit_epoch(struct KalicoRuntime *rt);

/**
 * Read the cumulative-accepted segment id cursor (§5.3 + §4.1.5).
 * Mirrors the value placed into the `kalico_push_response` schema.
 */
uint32_t runtime_handle_accepted_segment_id(struct KalicoRuntime *rt);

/**
 * Read the retired-through segment id cursor (§5.3 + §4.1.5). Advances
 * monotonically as the engine retires segments — host uses this to
 * gate flow control and to know when a stream-terminal hand-off is
 * safe to call.
 */
uint32_t runtime_handle_retired_through_segment_id(struct KalicoRuntime *rt);

/**
 * 2026-05-17 F4-retire-stall diagnostic: read low 32 bits of the most
 * recent `now - seg.t_start` observed inside `runtime_modulated_tick`.
 * `0` if no segment has been processed yet OR if the engine clock is
 * behind the segment's t_start (saturating_sub clamps to 0).
 */
uint32_t runtime_handle_last_modulated_elapsed_lo(struct KalicoRuntime *rt);

/**
 * Companion to `runtime_handle_last_modulated_elapsed_lo`: low 32 bits
 * of the active segment's `duration()`. If `elapsed_lo` >= this value,
 * the retirement branch should fire on the next tick.
 */
uint32_t runtime_handle_last_modulated_duration_lo(struct KalicoRuntime *rt);

/**
 * Number of times `runtime_modulated_tick`'s retirement branch was
 * entered (`elapsed >= duration` was true). Pair with the success
 * counter via `runtime_handle_modulated_retire_successes` to decide
 * whether retirement is failing on the `consumers_done` check.
 */
uint32_t runtime_handle_modulated_retire_attempts(struct KalicoRuntime *rt);

/**
 * Number of times `runtime_modulated_tick` actually retired a segment
 * (`consumers_done` was true after clearing the motor bits). If this
 * is less than `runtime_handle_modulated_retire_attempts`, some entries
 * to the retirement branch are still leaving consumer bits set.
 */
uint32_t runtime_handle_modulated_retire_successes(struct KalicoRuntime *rt);

/**
 * Last snapshot of seg.consumers_remaining AFTER the clear-all-motors
 * loop in modulated_tick's retirement branch. If retire_attempts >
 * retire_successes and this is non-zero, the bits in this value are
 * what the per-motor clear didn't reach.
 */
uint32_t runtime_handle_last_retire_consumers_after_clear(struct KalicoRuntime *rt);

/**
 * Read the currently-active segment id (`0` if engine is Idle/Drained
 * or pre-stream).
 */
uint32_t runtime_handle_current_segment_id(struct KalicoRuntime *rt);

/**
 * Approximate queue depth — number of segments the foreground has
 * pushed minus the number the ISR has retired through. Useful as a
 * status-frame breadcrumb but NOT a synchronization primitive (both
 * cursors lag the actual SPSC state by an unbounded number of ticks
 * in the worst case). Returns saturating-subtraction in u8 range
 * (`Q_N - 1` is the structural cap; saturate at 255 just in case).
 */
uint8_t runtime_handle_queue_depth(struct KalicoRuntime *rt);

/**
 * Read the latched `fault_detail` payload (§9.2). Mirrors the value
 * the foreground emits with the async `kalico_fault` event. `0` when
 * no fault has latched OR the latched fault carries no detail.
 */
uint32_t runtime_handle_fault_detail(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the configured `steps_per_mm` for axis `oid` (0..=3
 * in motor space). Returns 0.0 if `oid` is out of range or runtime
 * uninitialised. Used by Phase 4 sim test to verify that
 * `configure_axes_blob` reached the engine.
 */
float runtime_handle_get_axis_steps_per_mm(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Seed the engine's widen state with a u64 baseline so the engine's
 * `now` agrees with Klipper's widened MCU clock. Called by the Linux
 * sim host once at runtime_init, BEFORE the engine pthread starts
 * ticking. `baseline_widened_clock` is whatever value timer_read_time()
 * would map to in the widened (no-wrap) frame at this instant; the
 * caller computes it from clock_gettime so wrap counts already passed
 * in u32 timer_read_time space are folded in.
 */
void runtime_handle_seed_widen(struct KalicoRuntime *rt, uint64_t baseline_widened_clock);

/**
 * Diagnostic: read most recent post-PA/IS motor position for axis `oid`.
 */
float kalico_runtime_get_axis_motor(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Diagnostic: read most recent (now, t_start, duration) into the three
 * out pointers. All u64 cycle counts.
 */
void kalico_runtime_get_last_timing(struct KalicoRuntime *rt,
                                    uint64_t *now_out,
                                    uint64_t *t_start_out,
                                    uint64_t *duration_out);

/**
 * Diagnostic: read step accumulator (sub-step residual + integer state)
 * for axis `oid`.  Returns 0.0 if invalid.
 */
double kalico_runtime_get_axis_accumulator(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Read the cumulative signed step count for stepper `oid` (0-indexed).
 * Returns 0 for an invalid `rt` / uninitialised runtime / out-of-range oid.
 * Used by the sim diagnostic command `runtime_sim_stepper_count_query`.
 */
int32_t kalico_runtime_get_stepper_count(struct KalicoRuntime *rt, uint8_t oid);

/**
 * Configure axis mapping and kinematics for this MCU. Minimal stub for
 * Step 7-B MVP — accepts `kinematics_tag` (0 = CoreXyAndE, 1 =
 * CartesianXyzAndE) and validates. Full motor-config blob
 * deserialization is deferred to Step 7-C.
 */
int32_t kalico_configure_axes(struct KalicoRuntime *rt, uint8_t kinematics_tag);

/**
 * Extended blob layout (25 bytes) and phase-stepping blob layout
 * (33 bytes — Task 4 / spec §4.1):
 *
 * ```text
 * byte  0     kinematics_tag  (0 = CoreXY+E, 1 = Cartesian+E)
 * byte  1     present_mask    (bit i set → motor i is present)
 * byte  2     awd_mask        (bit i set → motor i is AWD)
 * byte  3     invert_mask     (bit i set → motor i direction inverted)
 * bytes 4-7   steps_per_mm[0] (f32 LE)
 * bytes 8-11  steps_per_mm[1] (f32 LE)
 * bytes 12-15 steps_per_mm[2] (f32 LE)
 * bytes 16-19 steps_per_mm[3] (f32 LE)
 *             -- present only in extended (25-byte) format --
 * byte 20     mcu_caps        (bit 0 = mcu_supports_phase_stepping)
 * byte 21     step_mode[0]    (0 = Modulated, 1 = StepTime)
 * byte 22     step_mode[1]
 * byte 23     step_mode[2]
 * byte 24     step_mode[3]
 *             -- present only in phase-stepping (26+3N-byte) format --
 * byte 25                 phase_motor_count = N (1..=MAX_STEPPER_OIDS)
 * bytes 26+3i..26+3i+2    motor i: (bus_id, cs_pin_id, slot_idx)
 * ```
 *
 * Legacy hosts emit the 20-byte format; the MCU defaults all steppers to
 * `StepTime` in that case. Any `blob_len` not in
 * `{20, 25, 26 + 3·N for 0 <= N <= MAX_STEPPER_OIDS}` is rejected. The
 * variable-length format requires `step_mode[slot_idx] == Modulated`
 * for every motor entry (spec §4.1). N is bounded by MAX_STEPPER_OIDS
 * (16); the earlier audible-band ≤2 cap is no longer enforced here —
 * per-shared-SPI-bus bandwidth derating is a separate future change.
 */
int32_t kalico_runtime_configure_axes_blob(struct KalicoRuntime *rt,
                                           const uint8_t *blob_ptr,
                                           uint32_t blob_len);

/**
 * Seed the engine's `prev_x/y/z` position origin and `StepMotorState`
 * accumulators so the first segment after `SET_KINEMATIC_POSITION`
 * computes its delta against the correct origin rather than `(0, 0, 0)`.
 *
 * Called by the C `DECL_COMMAND` handler for `runtime_seed_position`
 * immediately before the host sends the first `PushSegment` of the
 * new stream. Fire-and-forget from the host side; no response is
 * required because the following `PushSegment` provides ordering.
 *
 * `x_q16`, `y_q16`, `z_q16` are Q16.16 fixed-point mm values
 * (`i32 = mm * 65536`). Decoded to `f32` here; the precision loss
 * (≈ 15 µm at 1 m) is negligible relative to the step-size floor.
 *
 * Foreground-only. Projects `&mut IsrState` under the same
 * single-threaded-foreground precondition as `configure_axes_blob`.
 */
int32_t kalico_runtime_seed_position(struct KalicoRuntime *rt,
                                     int32_t x_q16,
                                     int32_t y_q16,
                                     int32_t z_q16);

/**
 * Phase 11 Task 11.2 foreground reclaim drain pipeline. Drains up to
 * `limit` trace samples from the ring, calls `pool.confirm_retired`
 * for each `SEGMENT_END` observed, and returns a 32-bit packed
 * status:
 *
 * - Bits 0..=15 — count of samples drained this call.
 * - Bit 16     — set if a fresh trace-overflow fault latched (§13.1).
 * - Bit 17     — set if at least one `SEGMENT_END` was observed
 *   (caller emits one or more `kalico_credit_freed`
 *   events keyed off the updated cursors).
 *
 * The C handler (`runtime_drain` `DECL_TASK` in `src/runtime_tick.c`)
 * uses this single-call form so the trace-drain + reclaim + fault-
 * latch pipeline is one round-trip per drain wake-up.
 */
uint32_t kalico_runtime_drain_and_reclaim(struct KalicoRuntime *rt, uint32_t limit);

/**
 * `kalico_stream_open` — assert host-MCU stream identity (§8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_open(struct KalicoRuntime *rt,
                                   uint32_t stream_id,
                                   uint32_t *out_credit_epoch);

/**
 * `kalico_stream_arm` — commit the priming buffer (§6.4 / §8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_arm(struct KalicoRuntime *rt,
                                  uint64_t t_start_t0,
                                  uint32_t arm_lead_cycles,
                                  uint64_t *out_armed_t_start);

/**
 * `kalico_stream_terminal` — mark the last segment id of the stream
 * (§8.3). Phase-6 stub.
 */
int32_t kalico_runtime_stream_terminal(struct KalicoRuntime *rt, uint32_t segment_id);

/**
 * `kalico_stream_flush` — `force_idle` handshake (§8.5).
 *
 * `flush()` projects to both halves under disabled-IRQ, so we hand it
 * the raw `*mut RuntimeContext` directly rather than going through
 * the foreground-only `project_fg` helper. SAFETY: caller is the
 * single-threaded foreground command dispatch.
 */
int32_t kalico_runtime_stream_flush(struct KalicoRuntime *rt, uint32_t *out_credit_epoch);

/**
 * `kalico_clock_sync_request` — RTT-aware clock-sync ping (§12.1).
 *
 * Returns the on-demand widened MCU clock (timer_read_time +
 * stats_send_time_high), NOT the engine seqlock value. Rationale: the
 * seqlock published by `Engine::tick` is only updated from the TIM5 ISR,
 * and TIM5 stays disabled in the all-StepTime MVP (see
 * `runtime_tick_enable` in `src/stm32/runtime_tick_h7.c` — early-return
 * when `count_modulated_steppers == 0`). Reading the seqlock in that
 * configuration returns its default 0, which the bridge's clock-sync
 * driver filters out as "MCU clock looks uninitialised" — the host's
 * router clock estimate then never refreshes from its connect-time
 * anchor, `compute_ack_clock` extrapolates linearly into the future,
 * segment `t_start` lands tens of seconds ahead of the MCU's actual
 * clock, and the in-flight credit window deadlocks waiting for
 * retirements that can't happen.
 *
 * The on-demand widening uses Klipper's `stats_send_time_high` (updated
 * by the stats DECL_TASK at ~0.2 Hz). Its ~5 s lag in the high half is
 * invisible to the bridge's RTT-aware linear regression — the
 * regression amortises samples over many ticks.
 */
int32_t kalico_runtime_clock_sync_request(struct KalicoRuntime *rt,
                                          uint32_t request_id,
                                          uint32_t host_send_time_lo,
                                          uint32_t host_send_time_hi,
                                          uint64_t *out_mcu_clock);

/**
 * Arm an endstop. The blob layouts match spec §3.1:
 * - `sources`: `source_count` records of 11 bytes each
 *   (kind u8, gpio u16 LE, polarity u8, arm_policy u8, sample_n u8,
 *    velocity_axis u8, v_min_q16 u32 LE).
 * - `steppers`: `stepper_count` records of 1 byte (stepper_oid u8).
 *
 * Writes one of the spec §3.2 status values into `*out_status`:
 * 0 = Armed, 1 = AlreadyTripped, 2 = Rejected.
 */
int32_t kalico_endstop_arm(uint32_t arm_id,
                           uint32_t arm_clock_lo,
                           uint32_t arm_clock_hi,
                           uint8_t source_count,
                           const uint8_t *sources_ptr,
                           uintptr_t sources_len,
                           uint8_t stepper_count,
                           const uint8_t *steppers_ptr,
                           uintptr_t steppers_len,
                           uint8_t *out_status);

/**
 * Disarm an active endstop arm. `out_status` writes spec §3.5 codes:
 * 0 = Disarmed, 1 = AlreadyTripped, 2 = Unknown.
 */
int32_t kalico_endstop_disarm(uint32_t arm_id, uint8_t *out_status);

/**
 * Drain the next pending trip event into a host-side buffer.
 *
 * Wire format v1, little-endian, total length =
 * `KALICO_TRIP_EVENT_V1_HEADER_LEN + stepper_count *
 * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN`. Header layout:
 * `arm_id u32 | trip_clock_lo u32 | trip_clock_hi u32 |
 *  trip_source_idx u8 | fmt_version u8 (=1) | stepper_count u8`.
 * Each stepper record: `stepper_oid u8 | step_count i32`.
 *
 * Returns:
 * - `1`  + `*out_actual_len` = encoded length: an event was drained.
 * - `0`  + `*out_actual_len = 0`: no event ready.
 * - `KALICO_ERR_NULL_PTR` on argument errors (incl. out_buf too small).
 */
int32_t kalico_endstop_poll_trip(uint8_t *out_buf,
                                 uintptr_t out_buf_len,
                                 uintptr_t *out_actual_len);

/**
 * Push a sampled GPIO level into the runtime's abstract pin table.
 *
 * The runtime's endstop module reads pin levels from an internal
 * `PIN_LEVELS: [AtomicBool; MAX_GPIO_PINS]` table (rust/runtime/src/
 * endstop.rs:311). The C ISR shim samples real GPIOs via
 * `gpio_in_read` once per modulation tick (TIM5_IRQHandler at
 * src/stm32/runtime_tick_h7.c, just before `runtime_handle_tick`)
 * and pushes each result through this FFI before `endstop::tick`
 * observes it. Sim builds (Renode e2e at
 * tools/test_renode_endstop_e2e.py) call the same FFI directly via
 * the `command_runtime_sim_endstop_set_pin` shim, bypassing real GPIO.
 */
int32_t kalico_endstop_set_pin_level(uint16_t gpio, uint8_t level);

/**
 * Step-time trip evaluation. Called from each `step_time_event` ISR
 * after the per-step GPIO sample, mirroring what `engine.tick()` does
 * for the Modulated path (which dispatches `endstop::tick` via
 * `engine::poll_endstop_trip`, see `rust/runtime/src/engine.rs`).
 *
 * In a StepTime-only firmware build (MVP), TIM5 — and therefore
 * `engine.tick` and its embedded `endstop::tick` call — never runs.
 * Without this entry point an armed endstop's per-step samples update
 * `PIN_LEVELS` but trip evaluation never happens, and homing moves
 * run forever even when the GPIO asserts.
 *
 * On `AbortNow` this also calls `Engine::abort_for_step_time_trip`
 * (the shared `abort_for_homing_trip` helper under the hood), which
 * retires every in-flight segment's curve-pool slots, publishes the
 * retire cursor for the host's `kalico_credit_freed` emitter, and
 * transitions the engine to `Drained`. Without that retirement, the
 * host's slot pool deadlocks after CURVE_POOL_N / 2 G28 trips
 * because trip-aborted segments leak their slots — observed in the
 * `g28_shaped_xy_two_pass_homing_via_renode_monitor` sim test.
 *
 * `now` is the widened MCU clock at the call site (same widening as
 * `command_runtime_clock_sync_request` uses). The endstop module
 * records this as the `trip_clock` in the published snapshot, and
 * gates on `now >= arm_clock`. Velocity-gated policies receive
 * `[u32::MAX; 3]` from this entry — see
 * `Engine::abort_for_step_time_trip` for the rationale.
 *
 * Returns 1 if a trip fired this call, 0 otherwise, or a negative
 * `KALICO_ERR_*` on misuse.
 */
int32_t kalico_endstop_tick_step_time(struct KalicoRuntime *rt, uint64_t now);

/**
 * Flip a stepper's `StepMode` at runtime. Spec §10.
 *
 * `mode`: 0 = Modulated (phase-stepping), 1 = StepTime (classic).
 * `mcu_supports_phase`: non-zero if the MCU advertises phase-stepping
 * capability.
 *
 * Returns:
 * - `KALICO_OK` on success.
 * - `KALICO_ERR_INVALID_HANDLE` if `handle` is null or
 *   `stepper_idx >= MAX_STEPPER_OIDS`.
 * - `KALICO_ERR_INVALID_ARG` if `mode` is not a recognised `StepMode`
 *   discriminant.
 * - `KALICO_ERR_CAPABILITY_MISSING` if `mode == Modulated` and
 *   `mcu_supports_phase == 0`.
 */
int32_t kalico_runtime_set_step_mode(struct KalicoRuntime *rt,
                                     uint8_t stepper_idx,
                                     uint8_t mode,
                                     uint8_t mcu_supports_phase);

/**
 * Flip the `phase_trace_enabled` gate (2026-05-18 plan Task 5).
 *
 * When enabled, `Engine::producer_step` / `runtime_modulated_tick`
 * push one `TRACE_FLAG_PHASE_STEP`-flagged `TraceSample` per
 * phase-stepping tick per motor (Task 6 wiring). Default is `false`;
 * production builds leave it off so the trace ring isn't burned by
 * the 80 kHz per-motor PhaseStep stream when no diagnostic is active.
 *
 * `enabled`: non-zero → true, zero → false. The store uses `Release`
 * ordering; the ISR-side load pairs with `Acquire`.
 *
 * Returns:
 * - `KALICO_OK` on success.
 * - `KALICO_ERR_NULL_PTR` if `rt` is null.
 * - `KALICO_ERR_NOT_INIT` if the runtime has not been initialised.
 */
int32_t kalico_runtime_set_phase_trace_enabled(struct KalicoRuntime *rt, uint8_t enabled);

/**
 * Producer Klipper-timer callback entry. Runs one `Engine::producer_step`
 * pass: Newton-fills `(cycles_abs_lo, dir)` entries into every StepTime
 * motor's `StepRing` up to `PRODUCER_BATCH_CAP` per motor, retires any
 * segment whose `consumers_remaining` mask drained, and republishes
 * `producer_pending` / `producer_runs_total` diagnostics.
 *
 * Returns `true` if at least one motor still has unfinished work
 * (caller should self-reschedule the producer timer); `false` if every
 * StepTime motor reached `AllIdle` (caller waits for a wake from
 * `push_segment`'s CAS or from `kalico_runtime_kick_producer`).
 *
 * SAFETY (caller): `rt` is the published `RT_CELL` pointer and the
 * producer-side Klipper timer is the single serialised caller — no
 * other context may concurrently form `&mut IsrState::engine` or
 * pull from `IsrState::queue_consumer`. The C-side producer timer in
 * Task 8 will enforce this by routing through one `DECL_TIMER`.
 */
bool kalico_runtime_producer_step(struct KalicoRuntime *rt);

/**
 * Per-motor consumer: peek the entry at the cursor without advancing.
 *
 * Returns `true` and writes `*out_cycles_abs_lo` + `*out_dir` if the
 * ring has at least one entry to consume; returns `false` (and leaves
 * the out-params untouched) on:
 *   - null `rt`, null out-params, or `motor_idx >= 4`;
 *   - `INIT_DONE == false`;
 *   - the ring is empty (producer hasn't caught up).
 *
 * SAFETY (caller): the per-stepper consumer Klipper timer (Task 7) is
 * the single serialised consumer of motor `motor_idx`'s ring; concurrent
 * `peek_*` / `advance` against the same motor from another context is
 * outside the SPSC contract.
 */
bool kalico_runtime_step_ring_peek_head(struct KalicoRuntime *rt,
                                        uint8_t motor_idx,
                                        uint32_t *out_cycles_abs_lo,
                                        int8_t *out_dir);

/**
 * Per-motor consumer: peek the second entry (the one after the cursor's
 * head). Used by the per-stepper consumer ISR to compute its next
 * reschedule time and decide whether the next pulse already has a
 * known direction (no DIR flip required).
 *
 * Same return / safety contract as `kalico_runtime_step_ring_peek_head`,
 * but reports `false` if fewer than two entries are available.
 */
bool kalico_runtime_step_ring_peek_next(struct KalicoRuntime *rt,
                                        uint8_t motor_idx,
                                        uint32_t *out_cycles_abs_lo,
                                        int8_t *out_dir);

/**
 * Per-motor consumer: advance the cursor past `n` entries. Called
 * after the per-stepper consumer Klipper timer has fired the step
 * pulse(s) corresponding to the entries up to (but not including) the
 * new cursor.
 *
 * `Release` ordering on the cursor (via `StepRing::advance`) pairs
 * with the producer's `Acquire` load in `StepRing::space`, publishing
 * that the consumed slots are free for the producer to overwrite.
 *
 * No-op on null `rt`, `motor_idx >= 4`, or before init completes.
 *
 * SAFETY (caller): see `kalico_runtime_step_ring_peek_head`. The
 * consumer Klipper timer is the single serialised caller of `advance`
 * for its motor.
 */
void kalico_runtime_step_ring_advance(struct KalicoRuntime *rt, uint8_t motor_idx, uint32_t n);

/**
 * Per-motor consumer: read the count of entries currently available
 * to consume (i.e. `head - cursor` with wrap-aware arithmetic).
 *
 * Used by the consumer Klipper timer's low-water hook to decide if it
 * should call `kalico_runtime_kick_producer` (e.g. when the ring is
 * below half full and the producer is currently idle waiting on a
 * kick).
 *
 * Returns `0` on null `rt`, `motor_idx >= 4`, or before init completes.
 */
uint32_t kalico_runtime_step_ring_available(struct KalicoRuntime *rt, uint8_t motor_idx);

/**
 * Wake the producer: CAS-set `shared.producer_pending` from `false`
 * to `true`. Returns `true` iff this call won the CAS — in which case
 * the caller is responsible for actually scheduling the producer
 * Klipper timer (`sched_add_timer` on the C side, Task 8). Returns
 * `false` if `producer_pending` was already `true` (another kicker
 * got there first; their scheduled producer run will see this
 * caller's wake reason).
 *
 * Wake sources covered by this entry point:
 *   - the per-motor consumer's low-water hook (Task 7);
 *   - any host-side reason to force a producer fill before the next
 *     `push_segment` arrives.
 *
 * `push_segment` already CAS-sets `producer_pending` inside
 * `Engine::push_segment` (rust/runtime/src/engine.rs); call sites
 * invoking `runtime_handle_push_segment` do NOT need to also call
 * this — the engine wakes itself.
 */
bool kalico_runtime_kick_producer(struct KalicoRuntime *rt);

/**
 * 2026-05-18: ISR-driven "I just retired a segment, please re-fetch the
 * next one" signal. `runtime_modulated_tick`'s retire branch sets
 * `producer_pending = true` via `Ordering::Release` store (atomic, no
 * CAS, ISR-safe). The C-side foreground task (`runtime_drain` at 1 kHz)
 * reads this through this FFI accessor and arms the producer Klipper
 * timer when both `pending == true` and the timer is not already on
 * the scheduler.
 *
 * Why a separate accessor instead of reusing `kalico_runtime_kick_producer`:
 * that function does CAS false→true and reports "did I win the wake?".
 * If the ISR already set pending=true, the CAS fails and the function
 * returns `false` ("someone else owns the wake"). The C-side then
 * assumes the owner armed the timer — but the ISR can't arm the timer
 * (foreground-only API). This accessor lets foreground observe the
 * ISR-set pending bit and recover by arming the timer itself.
 *
 * Returns the current `producer_pending` value (true = wake pending).
 */
bool kalico_runtime_get_producer_pending(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the high-water mark for motor `motor_idx`'s step
 * ring. Returns the maximum `available()` value observed across the
 * runtime's lifetime. Used by the C-side fault_detail rotation (tag
 * 0xB2) to localise whether the producer has actually pushed entries
 * — `0` means "ring was never written" (Cardano returned no roots, or
 * `fetch_segment_for_motor` never returned a curve).
 *
 * Returns `0` on null `rt`, `motor_idx >= 4`, or before init completes.
 */
uint32_t kalico_runtime_ring_high_water(struct KalicoRuntime *rt, uint8_t motor_idx);

/**
 * Diagnostic: read the low 32 bits of `producer_steps_pushed_total`.
 * Number of successful `ring.push` calls across all motors.
 */
uint32_t kalico_runtime_steps_pushed_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the low 32 bits of
 * `producer_motor_finished_curve_total`. Number of times Cardano
 * returned SegmentExhausted in a `producer_step` loop (per motor,
 * summed). Distinguishes "Cardano can't find roots" from "fetch
 * returns None".
 */
uint32_t kalico_runtime_motor_finished_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the low 32 bits of `producer_segment_retired_total`.
 * Number of segments fully retired by `producer_step`.
 */
uint32_t kalico_runtime_segments_retired_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the low 32 bits of `producer_segment_dequeued_total`.
 * Number of segments pulled off the queue by `producer_step`.
 * If host sent N PushSegment but this stays at 0, segments aren't
 * reaching the engine queue (kalico_dispatch or runtime_handle_push_segment
 * dropping silently).
 */
uint32_t kalico_runtime_segments_dequeued_lo(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: count of `producer_step` entries that observed
 * `producer_current.is_none()` — i.e., reached the dequeue site at the
 * top of the function. Compared against `producer_segment_dequeued_total`:
 *   - observed_none ≈ dequeued: ISR not setting producer_current=None
 *                                after retire (producer_current sticky).
 *   - observed_none ≫ dequeued: queue.dequeue() returns None despite
 *                                queue having entries (SPSC consumer bug).
 */
uint32_t kalico_runtime_observed_none_lo(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: live snapshot of `engine.producer_current.is_some()`.
 * Distinguishes "producer_current is sticky-Some (ISR's clear-to-None
 * invisible to foreground)" from "producer_current is None but
 * queue.dequeue() returns None" — the latter is the SPSC-bug
 * hypothesis; the former is the memory-visibility hypothesis.
 *
 * Returns 1 if producer_current is Some, 0 if None.
 * Reads via the ISR-state projection without locks (best-effort
 * foreground snapshot). Foreground and ISR don't run concurrently
 * per §11.1, so the read sees a consistent value.
 */
uint8_t kalico_runtime_producer_current_is_some_diag(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: live snapshot of `queue_consumer.len()` —
 * the SPSC's view of how many segments are queued and visible to the
 * Consumer. Cross-check against `accepted_segment_id -
 * retired_through_segment_id` (host's view of queue depth):
 *   - queue.len() == queue_depth → SPSC is consistent; bug elsewhere.
 *   - queue.len() < queue_depth  → SPSC's Consumer can't see all the
 *                                   Producer's enqueued segments
 *                                   (memory visibility / write-buffer
 *                                   / cache issue, or queue corrupted).
 */
uint32_t kalico_runtime_queue_len_diag(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: snapshot of `queue_consumer.len()` AS SEEN
 * FROM PRODUCER_STEP. Compared against `kalico_runtime_queue_len_diag`
 * (read from status_drain, different call site). If the two disagree,
 * the SPSC's Consumer head/tail reads return different values
 * depending on the call site — a compiler / optimization / aliasing
 * issue rather than a memory-visibility race.
 */
uint32_t kalico_runtime_queue_len_from_producer_step_diag(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: producer_step's OWN view of
 * `engine.producer_current.is_some()`. Compared against
 * `kalico_runtime_producer_current_is_some_diag` (which reads from
 * status_drain via &IsrState). If they disagree, producer_current is
 * being read inconsistently across function boundaries — the
 * non-atomic field is being cached by the compiler despite
 * modulated_tick writing it from the ISR-borrow path.
 */
uint8_t kalico_runtime_producer_current_is_some_from_producer_step_diag(struct KalicoRuntime *rt);

/**
 * 2026-05-18 wedge diag: counter of how many times the gate has been
 * SET (producer_current=Some) and CLEARED (None). Combined 32-bit
 * value: low 16 bits = set_count, high 16 bits = cleared_count
 * (capped at u16::MAX each). If cleared_count stays at 0 despite
 * modulated_tick's retire branch supposedly running, the Rust
 * write_producer_current_present helper isn't actually executing
 * the write on the retire path.
 */
uint32_t kalico_runtime_producer_current_gate_counters_diag(struct KalicoRuntime *_rt);

/**
 * Diagnostic: read the low 32 bits of `producer_runs_total`. Tells
 * how many `Engine::producer_step` invocations have completed since
 * boot. If `step_time_producer_kicks` (C side) is incrementing but
 * `producer_runs_total` stays at 0, the kick path is broken between
 * the CAS and `sched_add_timer`.
 *
 * Returns `0` on null `rt` or before init completes.
 */
uint32_t kalico_runtime_producer_runs_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the low 32 bits of `producer_fetch_attempts_total`.
 * Bumps unconditionally at function entry — if 0 while
 * `producer_runs_total` is non-zero, the per-motor loop is filtering
 * every motor at the step_mode / step_distance / is_idle gates.
 */
uint32_t kalico_runtime_fetch_attempts_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the low 32 bits of `producer_enqueue_success_total`.
 * Bumps AFTER `fg.queue_producer.enqueue(seg)` returns Ok in
 * `push_segment_impl`. If non-zero while
 * `producer_segment_dequeued_total` is 0, the queue split is broken
 * (producer and consumer ends not sharing the backing buffer).
 */
uint32_t kalico_runtime_enqueue_success_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read low 32 bits of `producer_primary_resolved_total`.
 * Number of times pool.resolve(primary) returned Some in producer_step.
 */
uint32_t kalico_runtime_primary_resolved_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: low 32 bits of `producer_primary_stale_total`.
 * Counted when handle != UNUSED but pool.resolve returned None.
 */
uint32_t kalico_runtime_primary_stale_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: low 32 bits of `producer_primary_unused_total`.
 * Counted when handle is the UNUSED sentinel (stationary axis).
 */
uint32_t kalico_runtime_primary_unused_lo(struct KalicoRuntime *rt);

/**
 * Diagnostic: read the last result code from `push_segment_impl`.
 * 0 = KALICO_OK, negative = an error code (see error.rs). Updated on
 * every call regardless of outcome.
 */
int32_t kalico_runtime_last_push_segment_result(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis: read the low 32 bits of
 * `push_segment_all_unused_total`. If this counter advances during a
 * jog, the bridge sent push_segment frames with every handle set to
 * the UNUSED sentinel — the segment retires on producer dequeue
 * without ever invoking motor processing, which matches the
 * "energized but no motion" symptom.
 */
uint32_t kalico_runtime_push_seg_all_unused_lo(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis: read the packed last `x_handle` from
 * `push_segment_impl`. Layout: `(gen << 16) | slot_idx`. UNUSED
 * sentinel = 0xFFFE_FFFE.
 */
uint32_t kalico_runtime_last_push_x_handle(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis: read the packed last `y_handle` from
 * `push_segment_impl`.
 */
uint32_t kalico_runtime_last_push_y_handle(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis: read the last `consumers_remaining`
 * mask computed by `push_segment_impl`. Zero means every handle on
 * the most recent push_segment was UNUSED.
 */
uint32_t kalico_runtime_last_push_consumers_remaining(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis (CP capture). Raw f32 bits of cps[0]
 * (first control point, position at u=0) of piece 0 of the most
 * recently resolved primary X curve. For a 0.5mm pure-X jog
 * starting at X=125.0, expect 0x42FA0000 (= 125.0f). Captured only
 * for motor 0.
 */
uint32_t kalico_runtime_last_resolved_primary_cps_0(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis (CP capture). Raw f32 bits of cps[3]
 * (last control point, position at u=1) of piece 0 of the most
 * recently resolved primary X curve. For a 0.5mm pure-X jog from
 * X=125.0, expect 0x42FB0000 (= 125.5f). If `cps_0 == cps_3`, the
 * curve has zero displacement — `SegmentExhausted` from
 * `compute_next_step_time` is then expected, indicating a planner
 * bug (or wire-corruption that zeroed the displacement).
 */
uint32_t kalico_runtime_last_resolved_primary_cps_3(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis (CP capture). Raw f32 bits of cps[0]
 * of the COMBINED (post-CoreXY-mix) curve for motor 0 (A = X + Y).
 * For a 0.5mm pure-X jog from X=125, Y=100 (Y curve constant), the
 * combined motor-A position at u=0 is X+Y = 225.0 (0x43610000).
 * Compare with the raw primary cps_0: if raw is correct but
 * combined is unexpected, the kinematic mix or the Y constant
 * value is wrong.
 */
uint32_t kalico_runtime_last_combined_motor_a_cps_0(struct KalicoRuntime *rt);

/**
 * 2026-05-15 live diagnosis (CP capture). Raw f32 bits of cps[3]
 * of the COMBINED (post-CoreXY-mix) curve for motor 0. For a 0.5mm
 * pure-X jog from X=125, Y=100, expect 225.5 (0x43618000). If
 * `combined_cps_0 == combined_cps_3` while raw primary cps_0 !=
 * cps_3, the kinematic combination is cancelling the displacement
 * (wrong sign in `kine.combine`, or follower curve carrying the
 * negative of the driver curve's delta).
 */
uint32_t kalico_runtime_last_combined_motor_a_cps_3(struct KalicoRuntime *rt);

/**
 * Synchronous foreground flush. Spec §3.10 (Task 11).
 *
 * Drains the segment queue, retires every in-flight curve-pool slot,
 * resets every `StepRing` (head + cursor → 0), clears every
 * `ProducerState`, zeroes per-motor `StepAccumulator` residuals, and
 * clears the engine's `producer_current` + legacy `current` slots.
 * After this returns, the runtime is in the "fresh, no work" state:
 * subsequent `kalico_runtime_producer_step` / TIM5
 * `runtime_modulated_tick` invocations return immediately.
 *
 * **Caller contract:** no concurrent `kalico_runtime_producer_step`,
 * TIM5 ISR, or per-stepper consumer Klipper-timer access may be in
 * flight. The C side enforces this by either (a) calling under
 * `irq_save` (the Klipper-timer / ISR paths gate on IRQs), or
 * (b) serialising through the bridge command channel (which is
 * single-threaded on the Klipper foreground task). The host's flush
 * path satisfies (b).
 *
 * Returns `true` on success, `false` on null `rt` or pre-init.
 */
bool kalico_runtime_force_idle(struct KalicoRuntime *rt);

/**
 * Apply `delta_steps` to `shared.stepper_counts[stepper_idx]` atomically.
 *
 * Called by the C-side `step_time_event` ISR after `runtime_emit_step_pulses`
 * to commit the just-emitted step into the engine's step counter. Without
 * this, `arm_step_timer_for_stepper`'s `current_step` read stays at 0
 * forever and the Newton solver always solves for the FIRST step within
 * the active segment — the timer fires, emits a step, then computes the
 * same first-step time again and never advances along the curve (bench
 * wedge 2026-05-12: engine retired segments by virtue of `Engine::tick`'s
 * `now` advancing, but step pulses-per-second was capped at the
 * 1 kHz NO_STEP poll rate rather than the true Newton-iterated step rate).
 *
 * Mirrors `engine.rs:1067`'s `counter.fetch_add(step_result.n_steps, ...)`
 * for the polled-tick / Modulated path.
 *
 * Returns `KALICO_OK` or an error.
 */
int32_t kalico_runtime_apply_step(struct KalicoRuntime *rt,
                                  uint8_t stepper_idx,
                                  int32_t delta_steps);

/**
 * Read the current `StepMode` discriminant for `stepper_idx`.
 *
 * Used by the C-side `arm_step_time_steppers_after_push` to determine
 * whether a stepper should be registered with Klipper's scheduler (mode
 * `StepTime = 1`) or driven by the TIM5 ISR (mode `Modulated = 0`).
 *
 * Returns:
 * - `0`    — `StepMode::Modulated` (phase-stepping via TIM5 ISR).
 * - `1`    — `StepMode::StepTime`  (classic Klipper timer scheduling).
 * - `0xFF` — null `rt`, `INIT_DONE == false`, or `stepper_idx` out of range.
 */
uint8_t kalico_runtime_get_step_mode(struct KalicoRuntime *rt, uint8_t stepper_idx);

/**
 * Read back the parsed phase-stepping SPI config for motor `motor_idx`
 * (Task 4 / spec §4.1 introspection).
 *
 * Returns the packed `AtomicU16` payload: high byte = `spi_bus_id`, low
 * byte = `cs_pin_id`. `0xFFFF` means no phase config is installed on
 * that motor (the default), and is also returned for a null `rt`,
 * uninitialised runtime, or `motor_idx >= 4`.
 *
 * Use `runtime::phase_config::PhaseConfig::unpack` on the host side to
 * decode.
 */
uint16_t kalico_runtime_query_phase_config(struct KalicoRuntime *rt, uint8_t motor_idx);

/**
 * Count how many steppers are currently in `StepMode::Modulated`.
 *
 * Used by `runtime_tick_enable` (C-side, spec §6.3) to decide whether
 * TIM5 is needed: if the count is zero, TIM5 has no work and is left
 * disabled. F4 (no `PHASE_STEPPING` capability) always hits this path;
 * H7 in an all-StepTime config also leaves TIM5 idle.
 *
 * Returns `0` for a null `rt` or uninitialised runtime.
 */
uint8_t kalico_runtime_count_modulated_steppers(struct KalicoRuntime *rt);

/**
 * Returns 1 if motor `stepper_idx` is configured (has step_distance > 0
 * in its `ProducerState`), 0 otherwise. Used by C-side
 * `init_step_time_timers` to avoid enabling consumer Klipper timers
 * for unconfigured motors — without this gate every motor with the
 * default `StepMode::StepTime` gets a timer regardless of
 * configuration, and on Renode (1 µs quantum) the resulting
 * scheduler load drowns LoadCurve byte processing in the USART RX
 * FIFO.
 */
uint8_t kalico_runtime_motor_is_configured(struct KalicoRuntime *rt, uint8_t stepper_idx);

#endif  /* KALICO_RUNTIME_H */
