/*
* kalico_runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-28-layer-4-mcu-framework-stub-design.md.
*/


#ifndef KALICO_RUNTIME_H
#define KALICO_RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define KALICO_TRIP_EVENT_V1_HEADER_LEN 15

#define KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN 5

#define KALICO_TRIP_EVENT_V1_FMT_VERSION 1

#define KALICO_TRIP_EVENT_V1_MAX_LEN (KALICO_TRIP_EVENT_V1_HEADER_LEN + (MAX_STEPPERS * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN))

enum SourceKind {
  Physical = 0,
  TmcDiag = 1,
};
typedef uint8_t SourceKind;

enum ArmPolicy {
  TripImmediately = 0,
  WaitForClear = 1,
  IgnoreUntilMoving = 2,
};
typedef uint8_t ArmPolicy;

typedef struct SourceConfig SourceConfig;

typedef struct VelocityAxis VelocityAxis;

/**
 * The opaque type C sees — never dereferenced on the C side.
 * Matches spec §3.2 / §5.6 handle discipline.
 */
typedef struct KalicoRuntime {
  uint8_t _private[0];
} KalicoRuntime;

/**
 * Handle to a loaded curve. 32-bit packed `(slot_idx, generation)` per
 * spec §10.1. ABA-defeating: at `Q_N_MAX = 256` the u16 gen wraps over
 * `65536 - 256 = 65280` allocations, which exceeds any realistic in-flight
 * stale-handle window.
 */
typedef struct CurveHandle {
  uint16_t slot_idx;
  uint16_t generation;
} CurveHandle;
/**
 * Sentinel for hold segments (§6.5). The ISR short-circuits on the
 * `SEGMENT_FLAG_HOLD_SEGMENT` flag bit BEFORE looking up this handle, so
 * the sentinel is never resolved through `CurvePool::lookup`.
 */
#define CurveHandle_HOLD_SEGMENT_SENTINEL (CurveHandle){ .slot_idx = UINT16_MAX, .generation = UINT16_MAX }
/**
 * Sentinel for unused curve handle slots in multi-handle segment structs.
 * Distinct from `HOLD_SEGMENT_SENTINEL` to avoid confusion.
 */
#define CurveHandle_UNUSED_SENTINEL (CurveHandle){ .slot_idx = (UINT16_MAX - 1), .generation = (UINT16_MAX - 1) }

/**
 * Trace sample (§13.2). `repr(C)` aligned (NOT packed) to avoid unaligned
 * `u64` access on Cortex-M7. Carries `curve_handle` so foreground reclaim
 * (`drain_and_reclaim` → `pool.confirm_retired(handle)`) can route
 * `SEGMENT_END` events back to the right pool slot per §10.4.
 */
typedef struct TraceSample {
  uint64_t tick;
  float motor_a;
  float motor_b;
  float motor_z;
  float motor_e;
  uint32_t segment_id;
  struct CurveHandle curve_handle;
  uint8_t flags;
  uint8_t _pad[7];
} TraceSample;













extern void kalico_h7_enable_tim5(void);

extern void kalico_h7_disable_tim5(void);

extern uint32_t kalico_h7_read_cyccnt(void);

/**
 * Init-once. Spec §3.2.
 *
 * Returns a valid handle on the first successful call; null on any
 * subsequent call. The handle is the address of the static
 * `RuntimeContext` storage; its lifetime is `'static`.
 */
struct KalicoRuntime *kalico_runtime_init(void);

/**
 * Push a segment. Producer protocol per spec §4.4 + §10.1.
 *
 * Step 7-B: four per-axis curve handles (x, y, z, e) replace the single
 * `curve_handle_packed`. Each is a wire-encoded `(generation << 16) |
 * slot_idx`. `e_mode` selects the extruder evaluation strategy (0 =
 * CoupledToXy, 1 = Independent, 2 = Travel). `extrusion_ratio_bits` is
 * `f32::to_bits()` of the extrusion_per_xy_mm scalar for CoupledToXy mode.
 *
 * `out_accepted_segment_id` and `out_credit_epoch` may be NULL (host
 * callers that don't need them); when present they receive the values
 * published into `SharedState` on success — host caller sees the same
 * values via the `kalico_push_response` schema (§5.3).
 */
int32_t kalico_runtime_push_segment(struct KalicoRuntime *rt,
                                    uint32_t id,
                                    uint32_t x_handle_packed,
                                    uint32_t y_handle_packed,
                                    uint32_t z_handle_packed,
                                    uint32_t e_handle_packed,
                                    uint64_t t_start,
                                    uint64_t t_end,
                                    uint8_t kinematics,
                                    uint8_t e_mode,
                                    uint32_t extrusion_ratio_bits,
                                    uint32_t *out_accepted_segment_id,
                                    uint32_t *out_credit_epoch);

/**
 * Load a scalar curve into a slab slot. Producer-side validation rejects
 * bad data. Returns the freshly issued `(slot, gen)` packed handle via
 * `out_handle_packed` on success.
 *
 * Step 7-B: accepts scalar control points (1D). No weights (polynomial-only).
 */
int32_t kalico_runtime_load_curve(struct KalicoRuntime *rt,
                                  uint16_t slot_idx,
                                  const float *control_points_flat,
                                  uint16_t n_cp,
                                  const float *knots,
                                  uint16_t n_knots,
                                  uint8_t degree,
                                  uint32_t *out_handle_packed);

/**
 * Validate a versioned blob payload's leading version byte (§4.2).
 * Foreground entrypoint for the C handler that reads payload bytes off
 * the wire and routes the post-version-byte slice into the Step-5
 * flat-pointer load path. Returns `KALICO_OK` on a recognised version
 * or `KALICO_ERR_PROTOCOL_VERSION_UNSUPPORTED` otherwise.
 */
int32_t kalico_runtime_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

/**
 * Diagnostic: per-slot generation snapshot (spec §10.4 + Round-1 B9).
 * Used after a fault for host-side recovery decisions. Writes the
 * per-slot `current_gen` and `last_retired_gen` into the out-params.
 */
int32_t kalico_runtime_query_pool_state(struct KalicoRuntime *rt,
                                        uint16_t slot_idx,
                                        uint16_t *out_current_gen,
                                        uint16_t *out_last_retired_gen);

/**
 * ISR entrypoint. Spec §3.2 / §4.2.
 * `raw_cyccnt` is the raw 32-bit DWT->CYCCNT value; Rust widens to u64.
 * Skips null-check (caller is the C ISR shim with stable handle).
 */
void kalico_runtime_tick(struct KalicoRuntime *rt, uint32_t raw_cyccnt);

/**
 * Foreground drain. Returns count of samples written.
 *
 * Phase 11 §10.4 expansion: alongside writing the sample to the wire
 * buffer, this also calls `pool.confirm_retired` for any sample
 * carrying `TRACE_FLAG_SEGMENT_END`, so curve-pool slots get reclaimed
 * in lockstep with the trace ship-out (one drain pass = one
 * foreground-side wire emit + one reclaim cursor advance).
 *
 * `out_saw_segment_end` (optional, may be NULL): set to `1` on return
 * when the drain consumed at least one `TRACE_FLAG_SEGMENT_END`
 * sample, else `0`. Closure-review fix: `kalico_credit_freed` emission
 * in `runtime_drain` previously gated only on the second
 * (drain-and-reclaim) leg's bit, but the first leg routinely consumes
 * every `SEGMENT_END` under steady-state push, suppressing the credit
 * event and deadlocking host flow control. The C handler now ORs this
 * bit with the reclaim leg's bit.
 */
uint32_t kalico_runtime_drain_trace(struct KalicoRuntime *rt,
                                    struct TraceSample *out_buf,
                                    uint32_t out_cap,
                                    uint8_t *out_saw_segment_end);

uint8_t kalico_runtime_status(struct KalicoRuntime *rt);

int32_t kalico_runtime_last_error(struct KalicoRuntime *rt);

uint32_t kalico_runtime_tick_counter(struct KalicoRuntime *rt);

/**
 * Read the widened MCU clock (§11.4 seqlock). Returns the most recently
 * published u64 cycle count from the ISR. Safe to call from foreground
 * at any time — the seqlock retries if it sees a torn read.
 */
uint64_t kalico_runtime_widened_now(struct KalicoRuntime *rt);

/**
 * Read the credit-flow epoch counter (§5.3 + §10.4). Bumped on each
 * `kalico_stream_flush` so the host can detect mid-stream resets.
 */
uint32_t kalico_runtime_credit_epoch(struct KalicoRuntime *rt);

/**
 * Read the cumulative-accepted segment id cursor (§5.3 + §4.1.5).
 * Mirrors the value placed into the `kalico_push_response` schema.
 */
uint32_t kalico_runtime_accepted_segment_id(struct KalicoRuntime *rt);

/**
 * Read the retired-through segment id cursor (§5.3 + §4.1.5). Advances
 * monotonically as the engine retires segments — host uses this to
 * gate flow control and to know when a stream-terminal hand-off is
 * safe to call.
 */
uint32_t kalico_runtime_retired_through_segment_id(struct KalicoRuntime *rt);

/**
 * Read the currently-active segment id (`0` if engine is Idle/Drained
 * or pre-stream).
 */
uint32_t kalico_runtime_current_segment_id(struct KalicoRuntime *rt);

/**
 * Approximate queue depth — number of segments the foreground has
 * pushed minus the number the ISR has retired through. Useful as a
 * status-frame breadcrumb but NOT a synchronization primitive (both
 * cursors lag the actual SPSC state by an unbounded number of ticks
 * in the worst case). Returns saturating-subtraction in u8 range
 * (`Q_N - 1` is the structural cap; saturate at 255 just in case).
 */
uint8_t kalico_runtime_queue_depth(struct KalicoRuntime *rt);

/**
 * Read the latched `fault_detail` payload (§9.2). Mirrors the value
 * the foreground emits with the async `kalico_fault` event. `0` when
 * no fault has latched OR the latched fault carries no detail.
 */
uint32_t kalico_runtime_fault_detail(struct KalicoRuntime *rt);

/**
 * Set the homed gate. Called by the host after all axes have been
 * successfully homed. The ISR checks `shared.homed` before accepting
 * motion segments — until this is called, motion commands are rejected
 * with `KALICO_ERR_NOT_HOMED`.
 */
int32_t kalico_set_homed(struct KalicoRuntime *rt);

/**
 * Configure axis mapping and kinematics for this MCU. Minimal stub for
 * Step 7-B MVP — accepts `kinematics_tag` (0 = CoreXyAndE, 1 =
 * CartesianXyzAndE) and validates. Full motor-config blob
 * deserialization is deferred to Step 7-C.
 */
int32_t kalico_configure_axes(struct KalicoRuntime *rt, uint8_t kinematics_tag);

/**
 * Phase 11 Task 11.2 foreground reclaim drain pipeline. Drains up to
 * `limit` trace samples from the ring, calls `pool.confirm_retired`
 * for each `SEGMENT_END` observed, and returns a 32-bit packed
 * status:
 *
 * - Bits 0..=15 — count of samples drained this call.
 * - Bit 16     — set if a fresh trace-overflow fault latched (§13.1).
 * - Bit 17     — set if at least one `SEGMENT_END` was observed
 *   (caller emits one or more `kalico_credit_freed`
 *   events keyed off the updated cursors).
 *
 * The C handler (`runtime_drain` `DECL_TASK` in `src/runtime_tick.c`)
 * uses this single-call form so the trace-drain + reclaim + fault-
 * latch pipeline is one round-trip per drain wake-up.
 */
uint32_t kalico_runtime_drain_and_reclaim(struct KalicoRuntime *rt, uint32_t limit);

/**
 * `kalico_stream_open` — assert host-MCU stream identity (§8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_open(struct KalicoRuntime *rt,
                                   uint32_t stream_id,
                                   uint32_t *out_credit_epoch);

/**
 * `kalico_stream_arm` — commit the priming buffer (§6.4 / §8.3).
 * Phase-6 stub.
 */
int32_t kalico_runtime_stream_arm(struct KalicoRuntime *rt,
                                  uint64_t t_start_t0,
                                  uint32_t arm_lead_cycles,
                                  uint64_t *out_armed_t_start);

/**
 * `kalico_stream_terminal` — mark the last segment id of the stream
 * (§8.3). Phase-6 stub.
 */
int32_t kalico_runtime_stream_terminal(struct KalicoRuntime *rt, uint32_t segment_id);

/**
 * `kalico_stream_flush` — `force_idle` handshake (§8.5).
 *
 * `flush()` projects to both halves under disabled-IRQ, so we hand it
 * the raw `*mut RuntimeContext` directly rather than going through
 * the foreground-only `project_fg` helper. SAFETY: caller is the
 * single-threaded foreground command dispatch.
 */
int32_t kalico_runtime_stream_flush(struct KalicoRuntime *rt, uint32_t *out_credit_epoch);

/**
 * `kalico_clock_sync_request` — RTT-aware clock-sync ping (§12.1).
 * Phase-6 stub. Out-param receives the MCU local-clock value sampled
 * inside the FFI on success.
 */
int32_t kalico_runtime_clock_sync_request(struct KalicoRuntime *rt,
                                          uint32_t request_id,
                                          uint32_t host_send_time_lo,
                                          uint32_t host_send_time_hi,
                                          uint64_t *out_mcu_clock);

/**
 * Arm an endstop. The blob layouts match spec §3.1:
 * - `sources`: `source_count` records of 11 bytes each
 *   (kind u8, gpio u16 LE, polarity u8, arm_policy u8, sample_n u8,
 *    velocity_axis u8, v_min_q16 u32 LE).
 * - `steppers`: `stepper_count` records of 1 byte (stepper_oid u8).
 *
 * Writes one of the spec §3.2 status values into `*out_status`:
 * 0 = Armed, 1 = AlreadyTripped, 2 = Rejected.
 */
int32_t kalico_endstop_arm(uint32_t arm_id,
                           uint32_t arm_clock_lo,
                           uint32_t arm_clock_hi,
                           uint8_t source_count,
                           const uint8_t *sources_ptr,
                           uintptr_t sources_len,
                           uint8_t stepper_count,
                           const uint8_t *steppers_ptr,
                           uintptr_t steppers_len,
                           uint8_t *out_status);

/**
 * Disarm an active endstop arm. `out_status` writes spec §3.5 codes:
 * 0 = Disarmed, 1 = AlreadyTripped, 2 = Unknown.
 */
int32_t kalico_endstop_disarm(uint32_t arm_id, uint8_t *out_status);

/**
 * Drain the next pending trip event into a host-side buffer.
 *
 * Wire format v1, little-endian, total length =
 * `KALICO_TRIP_EVENT_V1_HEADER_LEN + stepper_count *
 * KALICO_TRIP_EVENT_V1_PER_STEPPER_LEN`. Header layout:
 * `arm_id u32 | trip_clock_lo u32 | trip_clock_hi u32 |
 *  trip_source_idx u8 | fmt_version u8 (=1) | stepper_count u8`.
 * Each stepper record: `stepper_oid u8 | step_count i32`.
 *
 * Returns:
 * - `1`  + `*out_actual_len` = encoded length: an event was drained.
 * - `0`  + `*out_actual_len = 0`: no event ready.
 * - `KALICO_ERR_NULL_PTR` on argument errors (incl. out_buf too small).
 */
int32_t kalico_endstop_poll_trip(uint8_t *out_buf,
                                 uintptr_t out_buf_len,
                                 uintptr_t *out_actual_len);

/**
 * Set the homed gate to `homed` (0 = clear, non-zero = set). Required
 * for §8 host-driven homed-state control. The legacy no-arg
 * `kalico_set_homed` (always-set-true) at line ~830 above is preserved
 * for backward compat per spec rev 4.
 */
int32_t kalico_set_homed_state(struct KalicoRuntime *rt, uint8_t homed);

#endif  /* KALICO_RUNTIME_H */
