name: Build test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            klippy:
              - 'klippy/**'
            klipper:
              - 'src/**'
              - 'lib/**'
              - 'test/**'
              - 'scripts/**'

      - name: Test Klipper build (changes to the C code)
        if: steps.changes.outputs.klipper == 'true'
        run: |
          docker pull dangerklippers/klipper-build:latest
          docker build -f scripts/Dockerfile-build -t dangerklippers/klipper-build:latest .

      - name: Test Klippy (Only)
        if: steps.changes.outputs.klippy == 'true' || steps.changes.outputs.klipper == 'true'
        run: |
          docker run -v $PWD:/klipper dangerklippers/klipper-build:latest --python 3.9  py.test -n auto
          docker run -v $PWD:/klipper dangerklippers/klipper-build:latest --python 3.10 py.test -n auto
          docker run -v $PWD:/klipper dangerklippers/klipper-build:latest --python 3.11 py.test -n auto
          docker run -v $PWD:/klipper dangerklippers/klipper-build:latest --python 3.12 py.test -n auto
          docker run -v $PWD:/klipper dangerklippers/klipper-build:latest --python 3.13 py.test -n auto
